export const mapRegionCode = (code: string): string => {
  const regionMap: { [key: string]: string } = {
    I: "Ilocos Region",
    II: "Cagayan Valley",
    III: "Central Luzon",
    NCR: "NCR",
    "IV-A": "CALABARZON",
    "IV-B": "MIMAROPA",
    V: "Bicol",
    VI: "Western Visayas",
    VII: "Central Visayas",
    VIII: "Eastern Visayas",
    XVIII: "Negros Island",
    IX: "Zamboanga Peninsula",
    X: "Northern Mindanao",
    XI: "Davao Region",
    XII: "Soccsksargen",
    XIII: "Caraga",
    XIV: "CAR",
    BARMM: "BARMM",
  };
  return regionMap[code] || code;
};

// Define locations array
export const locations = [
  "All Locations",
  "NL",
  "NGMA",
  "MM",
  "SGMA",
  "SL",
  "VIS",
  "MIN",
];

export interface Province {
  province: string;
  municipalities: string[];
}

export const provinces: Province[] = [
  {
    province: "Abra",
    municipalities: [
      "Bangued",
      "Boliney",
      "Bucay",
      "Bucloc",
      "Daguioman",
      "Danglas",
      "Dolores",
      "La Paz",
      "Lacub",
      "Lagangilang",
      "Lagayan",
      "Langiden",
      "Licuan-Baay",
      "Luba",
      "Malibcong",
      "Manabo",
      "Peñarrubia",
      "Pidigan",
      "Pilar",
      "Sallapadan",
      "San Isidro",
      "San Juan",
      "San Quintin",
      "Tayum",
      "Tineg",
      "Tubo",
      "Villaviciosa",
    ],
  },
  {
    province: "Agusan del Norte",
    municipalities: [
      "Buenavista",
      "Carmen",
      "Jabonga",
      "Kitcharao",
      "Las Nieves",
      "Magallanes",
      "Nasipit",
      "Remedios T. Romualdez",
      "Santiago",
      "Tubay",
      "Butuan City",
      "Cabadbaran City",
    ],
  },
  {
    province: "Agusan del Sur",
    municipalities: [
      "Bayugan City",
      "Bunawan",
      "Esperanza",
      "La Paz",
      "Loreto",
      "Prosperidad",
      "Rosario",
      "San Francisco",
      "San Luis",
      "Santa Josefa",
      "Sibagat",
      "Talacogon",
      "Trento",
      "Veruela",
    ],
  },
  {
    province: "Aklan",
    municipalities: [
      "Altavas",
      "Balete",
      "Banga",
      "Batan",
      "Buruanga",
      "Ibajay",
      "Kalibo",
      "Lezo",
      "Libacao",
      "Madalag",
      "Makato",
      "Malay",
      "Malinao",
      "Nabas",
      "New Washington",
      "Numancia",
      "Tangalan",
    ],
  },
  {
    province: "Albay",
    municipalities: [
      "Bacacay",
      "Camalig",
      "Daraga",
      "Guinobatan",
      "Jovellar",
      "Libon",
      "Malilipot",
      "Malinao",
      "Manito",
      "Oas",
      "Pio Duran",
      "Polangui",
      "Rapu-Rapu",
      "Santo Domingo",
      "Tiwi",
      "Legazpi City",
      "Ligao City",
      "Tabaco City",
    ],
  },
  {
    province: "Antique",
    municipalities: [
      "Anini-y",
      "Barbaza",
      "Belison",
      "Bugasong",
      "Caluya",
      "Culasi",
      "Hamtic",
      "Laua-an",
      "Libertad",
      "Pandan",
      "Patnongon",
      "San Jose",
      "San Remigio",
      "Sebaste",
      "Sibalom",
      "Tibiao",
      "Tobias Fornier",
      "Valderrama",
    ],
  },
  {
    province: "Apayao",
    municipalities: [
      "Calanasan",
      "Conner",
      "Flora",
      "Kabugao",
      "Luna",
      "Pudtol",
      "Santa Marcela",
    ],
  },
  {
    province: "Aurora",
    municipalities: [
      "Baler",
      "Casiguran",
      "Dilasag",
      "Dinalungan",
      "Dingalan",
      "Dipaculao",
      "Maria Aurora",
      "San Luis",
    ],
  },
  {
    province: "Basilan",
    municipalities: [
      "Akbar",
      "Al-Barka",
      "Hadji Mohammad Ajul",
      "Hadji Muhtamad",
      "Lantawan",
      "Maluso",
      "Sumisip",
      "Tabuan-Lasa",
      "Tipo-Tipo",
      "Tuburan",
      "Ungkaya Pukan",
      "Lamitan City",
      "Isabela City",
    ],
  },
  {
    province: "Bataan",
    municipalities: [
      "Abucay",
      "Bagac",
      "Dinalupihan",
      "Hermosa",
      "Limay",
      "Mariveles",
      "Morong",
      "Orani",
      "Orion",
      "Pilar",
      "Samal",
      "Balanga City",
    ],
  },
  {
    province: "Batanes",
    municipalities: [
      "Basco",
      "Itbayat",
      "Ivana",
      "Mahatao",
      "Sabtang",
      "Uyugan",
    ],
  },
  {
    province: "Batangas",
    municipalities: [
      "Agoncillo",
      "Alitagtag",
      "Balayan",
      "Balete",
      "Bauan",
      "Calaca",
      "Calatagan",
      "Cuenca",
      "Ibaan",
      "Laurel",
      "Lemery",
      "Lian",
      "Lobo",
      "Mabini",
      "Malvar",
      "Mataasnakahoy",
      "Nasugbu",
      "Padre Garcia",
      "Rosario",
      "San Jose",
      "San Juan",
      "San Luis",
      "San Nicolas",
      "San Pascual",
      "Santa Teresita",
      "Santo Tomas",
      "Taal",
      "Talisay",
      "Taysan",
      "Tingloy",
      "Tuy",
      "Batangas City",
      "Lipa City",
      "Tanauan City",
    ],
  },
  {
    province: "Benguet",
    municipalities: [
      "Atok",
      "Bakun",
      "Bokod",
      "Buguias",
      "Itogon",
      "Kabayan",
      "Kapangan",
      "Kibungan",
      "La Trinidad",
      "Mankayan",
      "Sablan",
      "Tuba",
      "Tublay",
      "Baguio City",
    ],
  },
  {
    province: "Biliran",
    municipalities: [
      "Almeria",
      "Biliran",
      "Cabucgayan",
      "Caibiran",
      "Culaba",
      "Kawayan",
      "Maripipi",
      "Naval",
    ],
  },
  {
    province: "Bohol",
    municipalities: [
      "Alburquerque",
      "Alicia",
      "Anda",
      "Antequera",
      "Baclayon",
      "Balilihan",
      "Batuan",
      "Bien Unido",
      "Bilar",
      "Buenavista",
      "Calape",
      "Candijay",
      "Carmen",
      "Catigbian",
      "Clarin",
      "Corella",
      "Cortes",
      "Dagohoy",
      "Danao",
      "Dauis",
      "Dimiao",
      "Duero",
      "Garcia Hernandez",
      "Guindulman",
      "Inabanga",
      "Jagna",
      "Jetafe",
      "Lila",
      "Loay",
      "Loboc",
      "Loon",
      "Mabini",
      "Maribojoc",
      "Panglao",
      "Pilar",
      "Presidente Carlos P. Garcia",
      "Sagbayan",
      "San Isidro",
      "San Miguel",
      "Sevilla",
      "Sierra Bullones",
      "Sikatuna",
      "Talibon",
      "Trinidad",
      "Tubigon",
      "Ubay",
      "Valencia",
      "Tagbilaran City",
    ],
  },
  {
    province: "Bukidnon",
    municipalities: [
      "Baungon",
      "Cabanglasan",
      "Damulog",
      "Dangcagan",
      "Don Carlos",
      "Impasug-ong",
      "Kadingilan",
      "Kalilangan",
      "Kibawe",
      "Kitaotao",
      "Lantapan",
      "Libona",
      "Malitbog",
      "Manolo Fortich",
      "Maramag",
      "Pangantucan",
      "Quezon",
      "San Fernando",
      "Sumilao",
      "Talakag",
      "Valencia City",
      "Malaybalay City",
    ],
  },
  {
    province: "Bulacan",
    municipalities: [
      "Angat",
      "Balagtas",
      "Baliuag",
      "Bocaue",
      "Bulakan",
      "Bustos",
      "Calumpit",
      "Doña Remedios Trinidad",
      "Guiguinto",
      "Hagonoy",
      "Marilao",
      "Norzagaray",
      "Obando",
      "Pandi",
      "Paombong",
      "Plaridel",
      "Pulilan",
      "San Ildefonso",
      "San Miguel",
      "San Rafael",
      "Santa Maria",
      "Malolos City",
      "Meycauayan City",
      "San Jose del Monte City",
    ],
  },
  {
    province: "Cagayan",
    municipalities: [
      "Abulug",
      "Alcala",
      "Allacapan",
      "Amulung",
      "Aparri",
      "Baggao",
      "Ballesteros",
      "Buguey",
      "Calayan",
      "Camalaniugan",
      "Claveria",
      "Enrile",
      "Gattaran",
      "Gonzaga",
      "Iguig",
      "Lal-lo",
      "Lasam",
      "Pamplona",
      "Peñablanca",
      "Piat",
      "Rizal",
      "Sanchez-Mira",
      "Santa Ana",
      "Santa Praxedes",
      "Santa Teresita",
      "Santo Niño",
      "Solana",
      "Tuao",
      "Tuguegarao City",
    ],
  },
  {
    province: "Camarines Norte",
    municipalities: [
      "Basud",
      "Capalonga",
      "Daet",
      "Jose Panganiban",
      "Labo",
      "Mercedes",
      "Paracale",
      "San Lorenzo Ruiz",
      "San Vicente",
      "Santa Elena",
      "Talisay",
      "Vinzons",
    ],
  },
  {
    province: "Camarines Sur",
    municipalities: [
      "Baao",
      "Balatan",
      "Bato",
      "Bombon",
      "Buhi",
      "Bula",
      "Cabusao",
      "Calabanga",
      "Camaligan",
      "Canaman",
      "Caramoan",
      "Del Gallego",
      "Gainza",
      "Garchitorena",
      "Goa",
      "Lagonoy",
      "Libmanan",
      "Lupi",
      "Magarao",
      "Milaor",
      "Minalabac",
      "Nabua",
      "Ocampo",
      "Pamplona",
      "Pasacao",
      "Pili",
      "Presentacion",
      "Ragay",
      "Sagñay",
      "San Fernando",
      "San Jose",
      "Sipocot",
      "Siruma",
      "Tigaon",
      "Tinambac",
      "Iriga City",
      "Naga City",
    ],
  },
  {
    province: "Camiguin",
    municipalities: ["Catarman", "Guinsiliban", "Mahinog", "Mambajao", "Sagay"],
  },
  {
    province: "Capiz",
    municipalities: [
      "Cuartero",
      "Dao",
      "Dumalag",
      "Dumarao",
      "Ivisan",
      "Jamindan",
      "Ma-ayon",
      "Mambusao",
      "Panay",
      "Panitan",
      "Pilar",
      "Pontevedra",
      "President Roxas",
      "Sapi-an",
      "Sigma",
      "Tapaz",
      "Roxas City",
    ],
  },
  {
    province: "Catanduanes",
    municipalities: [
      "Bagamanoc",
      "Baras",
      "Bato",
      "Caramoran",
      "Gigmoto",
      "Pandan",
      "Panganiban",
      "San Andres",
      "San Miguel",
      "Viga",
      "Virac",
    ],
  },
  {
    province: "Cavite",
    municipalities: [
      "Alfonso",
      "Amadeo",
      "Carmona",
      "General Emilio Aguinaldo",
      "General Mariano Alvarez",
      "Indang",
      "Magallanes",
      "Maragondon",
      "Mendez",
      "Naic",
      "Noveleta",
      "Rosario",
      "Silang",
      "Tanza",
      "Ternate",
      "Bacoor City",
      "Cavite City",
      "Dasmariñas City",
      "General Trias City",
      "Imus City",
      "Tagaytay City",
      "Trece Martires City",
    ],
  },
  {
    province: "Cebu",
    municipalities: [
      "Alcantara",
      "Alcoy",
      "Alegria",
      "Aloguinsan",
      "Argao",
      "Asturias",
      "Bantayan",
      "Barili",
      "Boljoon",
      "Borbon",
      "Carmen",
      "Catmon",
      "Compostela",
      "Consolacion",
      "Cordova",
      "Daanbantayan",
      "Dalaguete",
      "Dumanjug",
      "Ginatilan",
      "Liloan",
      "Madridejos",
      "Malabuyoc",
      "Medellin",
      "Minglanilla",
      "Moalboal",
      "Oslob",
      "Pilar",
      "Pinamungajan",
      "Poro",
      "Ronda",
      "Samboan",
      "San Fernando",
      "San Francisco",
      "San Remigio",
      "Santa Fe",
      "Santander",
      "Sibonga",
      "Sogod",
      "Tabogon",
      "Tabuelan",
      "Tuburan",
      "Tudela",
      "Bogo City",
      "Carcar City",
      "Cebu City",
      "Danao City",
      "Lapu-Lapu City",
      "Mandaue City",
      "Naga City",
      "Talisay City",
      "Toledo City",
    ],
  },
  {
    province: "Cotabato",
    municipalities: [
      "Alamada",
      "Aleosan",
      "Antipas",
      "Arakan",
      "Banisilan",
      "Carmen",
      "Kabacan",
      "Kidapawan City",
      "Libungan",
      "M'lang",
      "Magpet",
      "Makilala",
      "Matalam",
      "Midsayap",
      "Pigcawayan",
      "Pikit",
      "President Roxas",
      "Tulunan",
    ],
  },
  {
    province: "Davao de Oro (Compostela Valley)",
    municipalities: [
      "Compostela",
      "Laak",
      "Mabini",
      "Maco",
      "Maragusan",
      "Mawab",
      "Monkayo",
      "Montevista",
      "Nabunturan",
      "New Bataan",
      "Pantukan",
    ],
  },
  {
    province: "Davao del Norte",
    municipalities: [
      "Asuncion",
      "Braulio E. Dujali",
      "Carmen",
      "Kapalong",
      "New Corella",
      "Panabo City",
      "Samal City",
      "San Isidro",
      "Santo Tomas",
      "Tagum City",
      "Talaingod",
    ],
  },
  {
    province: "Davao del Sur",
    municipalities: [
      "Bansalan",
      "Davao City",
      "Digos City",
      "Hagonoy",
      "Kiblawan",
      "Magsaysay",
      "Malita",
      "Matanao",
      "Padada",
      "Santa Cruz",
      "Sulop",
    ],
  },
  {
    province: "Davao Occidental",
    municipalities: [
      "Don Marcelino",
      "Jose Abad Santos",
      "Malita",
      "Santa Maria",
      "Sarangani",
    ],
  },
  {
    province: "Davao Oriental",
    municipalities: [
      "Baganga",
      "Banaybanay",
      "Boston",
      "Caraga",
      "Cateel",
      "Governor Generoso",
      "Lupon",
      "Manay",
      "Mati City",
      "San Isidro",
      "Tarragona",
    ],
  },
  {
    province: "Dinagat Islands",
    municipalities: [
      "Basilisa",
      "Cagdianao",
      "Dinagat",
      "Libjo",
      "Loreto",
      "San Jose",
      "Tubajon",
    ],
  },
  {
    province: "Eastern Samar",
    municipalities: [
      "Arteche",
      "Balangiga",
      "Balangkayan",
      "Borongan City",
      "Can-avid",
      "Dolores",
      "General MacArthur",
      "Giporlos",
      "Guiuan",
      "Hernani",
      "Jipapad",
      "Lawaan",
      "Llorente",
      "Maslog",
      "Maydolong",
      "Mercedes",
      "Oras",
      "Quinapondan",
      "Salcedo",
      "San Julian",
      "San Policarpo",
      "Sulat",
      "Taft",
    ],
  },
  {
    province: "Guimaras",
    municipalities: [
      "Buenavista",
      "Jordan",
      "Nueva Valencia",
      "San Lorenzo",
      "Sibunag",
    ],
  },
  {
    province: "Ifugao",
    municipalities: [
      "Aguinaldo",
      "Alfonso Lista",
      "Asipulo",
      "Banaue",
      "Hingyon",
      "Hungduan",
      "Kiangan",
      "Lagawe",
      "Lamut",
      "Mayoyao",
      "Tinoc",
    ],
  },
  {
    province: "Ilocos Norte",
    municipalities: [
      "Adams",
      "Bacarra",
      "Badoc",
      "Bangui",
      "Banna",
      "Batac City",
      "Burgos",
      "Carasi",
      "Currimao",
      "Dingras",
      "Dumalneg",
      "Laoag City",
      "Marcos",
      "Nueva Era",
      "Pagudpud",
      "Paoay",
      "Pasuquin",
      "Piddig",
      "Pinili",
      "San Nicolas",
      "Sarrat",
      "Solsona",
      "Vintar",
    ],
  },
  {
    province: "Ilocos Sur",
    municipalities: [
      "Alilem",
      "Banayoyo",
      "Bantay",
      "Burgos",
      "Cabugao",
      "Candon City",
      "Caoayan",
      "Cervantes",
      "Galimuyod",
      "Gregorio del Pilar",
      "Lidlidda",
      "Magsingal",
      "Nagbukel",
      "Narvacan",
      "Quirino",
      "Salcedo",
      "San Emilio",
      "San Esteban",
      "San Ildefonso",
      "San Juan",
      "San Vicente",
      "Santa",
      "Santa Catalina",
      "Santa Cruz",
      "Santa Lucia",
      "Santa Maria",
      "Santiago",
      "Santo Domingo",
      "Sigay",
      "Sinait",
      "Sugpon",
      "Suyo",
      "Tagudin",
      "Vigan City",
    ],
  },
  {
    province: "Iloilo",
    municipalities: [
      "Ajuy",
      "Alimodian",
      "Anilao",
      "Badiangan",
      "Balasan",
      "Banate",
      "Barotac Nuevo",
      "Barotac Viejo",
      "Batad",
      "Bingawan",
      "Cabatuan",
      "Calinog",
      "Carles",
      "Concepcion",
      "Dingle",
      "Dueñas",
      "Dumangas",
      "Estancia",
      "Guimbal",
      "Igbaras",
      "Janiuay",
      "Lambunao",
      "Leganes",
      "Lemery",
      "Leon",
      "Maasin",
      "Miagao",
      "Mina",
      "New Lucena",
      "Oton",
      "Pavia",
      "Pototan",
      "San Dionisio",
      "San Enrique",
      "San Joaquin",
      "San Miguel",
      "San Rafael",
      "Santa Barbara",
      "Sara",
      "Tigbauan",
      "Tubungan",
      "Zarraga",
      "Iloilo City",
      "Passi City",
    ],
  },
  {
    province: "Isabela",
    municipalities: [
      "Alicia",
      "Angadanan",
      "Aurora",
      "Benito Soliven",
      "Burgos",
      "Cabagan",
      "Cabatuan",
      "Cauayan City",
      "Cordon",
      "Delfin Albano",
      "Dinapigue",
      "Divilacan",
      "Echague",
      "Gamu",
      "Ilagan City",
      "Jones",
      "Luna",
      "Maconacon",
      "Mallig",
      "Naguilian",
      "Palanan",
      "Quezon",
      "Quirino",
      "Ramon",
      "Reina Mercedes",
      "Roxas",
      "San Agustin",
      "San Guillermo",
      "San Isidro",
      "San Manuel",
      "San Mariano",
      "San Mateo",
      "San Pablo",
      "Santa Maria",
      "Santiago City",
      "Santo Tomas",
      "Tumauini",
    ],
  },
  {
    province: "Kalinga",
    municipalities: [
      "Balbalan",
      "Lubuagan",
      "Pasil",
      "Pinukpuk",
      "Rizal",
      "Tabuk City",
      "Tanudan",
      "Tinglayan",
    ],
  },
  {
    province: "La Union",
    municipalities: [
      "Agoo",
      "Aringay",
      "Bacnotan",
      "Bagulin",
      "Balaoan",
      "Bangar",
      "Bauang",
      "Burgos",
      "Caba",
      "Luna",
      "Naguilian",
      "Pugo",
      "Rosario",
      "San Fernando City",
      "San Gabriel",
      "San Juan",
      "Santo Tomas",
      "Santol",
      "Sudipen",
      "Tubao",
    ],
  },
  {
    province: "Laguna",
    municipalities: [
      "Alaminos",
      "Bay",
      "Biñan City",
      "Cabuyao City",
      "Calamba City",
      "Calauan",
      "Cavinti",
      "Famy",
      "Kalayaan",
      "Liliw",
      "Los Baños",
      "Luisiana",
      "Lumban",
      "Mabitac",
      "Magdalena",
      "Majayjay",
      "Nagcarlan",
      "Paete",
      "Pagsanjan",
      "Pakil",
      "Pangil",
      "Pila",
      "Rizal",
      "San Pablo City",
      "San Pedro City",
      "Santa Cruz",
      "Santa Maria",
      "Santa Rosa City",
      "Siniloan",
      "Victoria",
    ],
  },
  {
    province: "Lanao del Norte",
    municipalities: [
      "Bacolod",
      "Baloi",
      "Bayang",
      "Binidayan",
      "Balo-i",
      "Kapatagan",
      "Kauswagan",
      "Kolambugan",
      "Lala",
      "Linamon",
      "Magsaysay",
      "Maigo",
      "Matungao",
      "Munai",
      "Nunungan",
      "Pantao Ragat",
      "Pantar",
      "Poona Piagapo",
      "Salvador",
      "Sapad",
      "Sultan Naga Dimaporo",
      "Tagoloan",
      "Tangcal",
      "Tubod",
      "Iligan City",
    ],
  },
  {
    province: "Lanao del Sur",
    municipalities: [
      "Amai Manabilang",
      "Bacolod-Kalawi",
      "Balabagan",
      "Balindong",
      "Bayang",
      "Binidayan",
      "Buadiposo-Buntong",
      "Bubong",
      "Butig",
      "Calanogas",
      "Ditsaan-Ramain",
      "Ganassi",
      "Kapai",
      "Kapatagan",
      "Lumba-Bayabao",
      "Lumbaca-Unayan",
      "Lumbatan",
      "Lumbayanague",
      "Madalum",
      "Madamba",
      "Maguing",
      "Malabang",
      "Marantao",
      "Marawi City",
      "Marogong",
      "Masiu",
      "Mulondo",
      "Pagayawan",
      "Piagapo",
      "Picong",
      "Poona Bayabao",
      "Pualas",
      "Saguiaran",
      "Sultan Dumalondong",
      "Tagoloan II",
      "Tamparan",
      "Taraka",
      "Tubaran",
      "Tugaya",
      "Wao",
    ],
  },
  {
    province: "Leyte",
    municipalities: [
      "Abuyog",
      "Alangalang",
      "Albuera",
      "Babatngon",
      "Barugo",
      "Bato",
      "Baybay City",
      "Burauen",
      "Calubian",
      "Capoocan",
      "Carigara",
      "Dagami",
      "Dulag",
      "Hilongos",
      "Hindang",
      "Inopacan",
      "Isabel",
      "Jaro",
      "Javier",
      "Julita",
      "Kananga",
      "La Paz",
      "Leyte",
      "MacArthur",
      "Mahaplag",
      "Matag-ob",
      "Matalom",
      "Mayorga",
      "Merida",
      "Ormoc City",
      "Palompon",
      "Pastrana",
      "San Isidro",
      "San Miguel",
      "Santa Fe",
      "Tabango",
      "Tabontabon",
      "Tacloban City",
      "Tanauan",
      "Tolosa",
      "Tunga",
      "Villaba",
    ],
  },
  {
    province: "Maguindanao del Norte",
    municipalities: [
      "Barira",
      "Buldon",
      "Datu Blah T. Sinsuat",
      "Datu Odin Sinsuat",
      "Kabuntalan",
      "Matanog",
      "Northern Kabuntalan",
      "Parang",
      "Sultan Kudarat",
      "Sultan Mastura",
      "Wao",
    ],
  },
  {
    province: "Maguindanao del Sur",
    municipalities: [
      "Ampatuan",
      "Buluan",
      "Datu Abdulah Sangki",
      "Datu Anggal Midtimbang",
      "Datu Hoffer Ampatuan",
      "Datu Montawal",
      "Datu Paglas",
      "Datu Piang",
      "Datu Salibo",
      "Datu Saudi-Ampatuan",
      "Datu Unsay",
      "General Salipada K. Pendatun",
      "Guindulungan",
      "Mamasapano",
      "Mangudadatu",
      "Pagalungan",
      "Pandag",
      "Rajah Buayan",
      "Shariff Aguak",
      "Shariff Saydona Mustapha",
      "South Upi",
      "Sultan sa Barongis",
      "Talayan",
      "Talitay",
      "Upi",
    ],
  },
  {
    province: "Marinduque",
    municipalities: [
      "Boac",
      "Buenavista",
      "Gasan",
      "Mogpog",
      "Santa Cruz",
      "Torrijos",
    ],
  },
  {
    province: "Masbate",
    municipalities: [
      "Aroroy",
      "Baleno",
      "Balud",
      "Batuan",
      "Cataingan",
      "Cawayan",
      "Claveria",
      "Dimasalang",
      "Esperanza",
      "Mandaon",
      "Masbate City",
      "Milagros",
      "Mobo",
      "Monreal",
      "Palanas",
      "Pio V. Corpuz",
      "Placer",
      "San Fernando",
      "San Jacinto",
      "San Pascual",
      "Uson",
    ],
  },
  {
    province: "Metro Manila",
    municipalities: [
      "Caloocan City",
      "Las Piñas City",
      "Makati City",
      "Malabon City",
      "Mandaluyong City",
      "Manila",
      "Marikina City",
      "Muntinlupa City",
      "Navotas City",
      "Parañaque City",
      "Pasay City",
      "Pasig City",
      "Pateros",
      "Quezon City",
      "San Juan City",
      "Taguig City",
      "Valenzuela City",
    ],
  },
  {
    province: "Misamis Occidental",
    municipalities: [
      "Aloran",
      "Baliangao",
      "Bonifacio",
      "Calamba",
      "Clarin",
      "Concepcion",
      "Don Victoriano Chiongbian",
      "Jimenez",
      "Lopez Jaena",
      "Oroquieta City",
      "Ozamiz City",
      "Panaon",
      "Plaridel",
      "Sapang Dalaga",
      "Sinacaban",
      "Tangub City",
      "Tudela",
    ],
  },
  {
    province: "Misamis Oriental",
    municipalities: [
      "Alubijid",
      "Balingasag",
      "Balingoan",
      "Binuangan",
      "Cagayan de Oro City",
      "Catarman",
      "Claveria",
      "El Salvador City",
      "Gingoog City",
      "Gitagum",
      "Initao",
      "Jasaan",
      "Kinoguitan",
      "Lagonglong",
      "Laguindingan",
      "Libertad",
      "Lugait",
      "Magsaysay",
      "Manticao",
      "Medina",
      "Naawan",
      "Opol",
      "Salay",
      "Sugbongcogon",
      "Tagoloan",
      "Talisayan",
      "Villanueva",
    ],
  },
  {
    province: "Mountain Province",
    municipalities: [
      "Barlig",
      "Bauko",
      "Besao",
      "Bontoc",
      "Natonin",
      "Paracelis",
      "Sabangan",
      "Sadanga",
      "Sagada",
      "Tadian",
    ],
  },
  {
    province: "Negros Occidental",
    municipalities: [
      "Bacolod City",
      "Bago City",
      "Binalbagan",
      "Cadiz City",
      "Calatrava",
      "Candoni",
      "Cauayan",
      "Enrique B. Magalona",
      "Escalante City",
      "Himamaylan City",
      "Hinigaran",
      "Hinoba-an",
      "Ilog",
      "Isabela",
      "Kabankalan City",
      "La Carlota City",
      "La Castellana",
      "Manapla",
      "Moises Padilla",
      "Murcia",
      "Pontevedra",
      "Pulupandan",
      "Sagay City",
      "Salvador Benedicto",
      "San Carlos City",
      "San Enrique",
      "Silay City",
      "Sipalay City",
      "Talisay City",
      "Toboso",
      "Valladolid",
      "Victorias City",
    ],
  },
  {
    province: "Negros Oriental",
    municipalities: [
      "Amlan",
      "Ayungon",
      "Bacong",
      "Bais City",
      "Basay",
      "Bayawan City",
      "Bindoy",
      "Canlaon City",
      "Dauin",
      "Dumaguete City",
      "Guihulngan City",
      "Jimalalud",
      "La Libertad",
      "Mabinay",
      "Manjuyod",
      "Pamplona",
      "San Jose",
      "Santa Catalina",
      "Siaton",
      "Sibulan",
      "Tanjay City",
      "Tayasan",
      "Valencia",
      "Vallehermoso",
      "Zamboanguita",
    ],
  },
  {
    province: "Northern Samar",
    municipalities: [
      "Allen",
      "Biri",
      "Bobon",
      "Capul",
      "Catarman",
      "Catubig",
      "Gamay",
      "Laoang",
      "Lapinig",
      "Las Navas",
      "Lavezares",
      "Lope de Vega",
      "Mapanas",
      "Mondragon",
      "Palapag",
      "Pambujan",
      "Rosario",
      "San Antonio",
      "San Isidro",
      "San Jose",
      "San Roque",
      "San Vicente",
      "Silvino Lobos",
      "Victoria",
    ],
  },
  {
    province: "Nueva Ecija",
    municipalities: [
      "Aliaga",
      "Bongabon",
      "Cabanatuan City",
      "Cabiao",
      "Carranglan",
      "Cuyapo",
      "Gabaldon",
      "Gapan City",
      "General Mamerto Natividad",
      "General Tinio",
      "Guimba",
      "Jaen",
      "Laur",
      "Licab",
      "Llanera",
      "Lupao",
      "Muñoz City",
      "Nampicuan",
      "Pantabangan",
      "Peñaranda",
      "Quezon",
      "Rizal",
      "San Antonio",
      "San Isidro",
      "San Jose City",
      "San Leonardo",
      "Santa Rosa",
      "Santo Domingo",
      "Talavera",
      "Talugtug",
      "Zaragoza",
    ],
  },
  {
    province: "Nueva Vizcaya",
    municipalities: [
      "Alfonso Castañeda",
      "Ambaguio",
      "Aritao",
      "Bagabag",
      "Bambang",
      "Bayombong",
      "Diadi",
      "Dupax del Norte",
      "Dupax del Sur",
      "Kasibu",
      "Kayapa",
      "Quezon",
      "Santa Fe",
      "Solano",
      "Villaverde",
    ],
  },
  {
    province: "Occidental Mindoro",
    municipalities: [
      "Abra de Ilog",
      "Calintaan",
      "Looc",
      "Lubang",
      "Magsaysay",
      "Mamburao",
      "Paluan",
      "Rizal",
      "Sablayan",
      "San Jose",
      "Santa Cruz",
    ],
  },
  {
    province: "Oriental Mindoro",
    municipalities: [
      "Baco",
      "Bansud",
      "Bongabong",
      "Bulalacao",
      "Calapan City",
      "Gloria",
      "Mansalay",
      "Naujan",
      "Pinamalayan",
      "Pola",
      "Puerto Galera",
      "Roxas",
      "San Teodoro",
      "Socorro",
      "Victoria",
    ],
  },
  {
    province: "Palawan",
    municipalities: [
      "Aborlan",
      "Agutaya",
      "Araceli",
      "Balabac",
      "Bataraza",
      "Brooke's Point",
      "Busuanga",
      "Cagayancillo",
      "Coron",
      "Culion",
      "Cuyo",
      "Dumaran",
      "El Nido",
      "Linapacan",
      "Magsaysay",
      "Narra",
      "Puerto Princesa City",
      "Quezon",
      "Rizal",
      "Roxas",
      "San Vicente",
      "Sofronio Española",
      "Taytay",
      "Kalayaan",
    ],
  },
  {
    province: "Pampanga",
    municipalities: [
      "Apalit",
      "Arayat",
      "Bacolor",
      "Candaba",
      "Floridablanca",
      "Guagua",
      "Lubao",
      "Macabebe",
      "Magalang",
      "Masantol",
      "Mexico",
      "Minalin",
      "Porac",
      "Sasmuan",
      "Santa Ana",
      "Santa Rita",
      "Santo Tomas",
      "Sta. Ana",
      "Angeles City",
      "Mabalacat City",
      "San Fernando City",
    ],
  },
  {
    province: "Pangasinan",
    municipalities: [
      "Agno",
      "Aguilar",
      "Alaminos City",
      "Alcala",
      "Anda",
      "Asingan",
      "Balungao",
      "Bani",
      "Basista",
      "Bautista",
      "Bayambang",
      "Binalonan",
      "Binmaley",
      "Bolinao",
      "Bugallon",
      "Burgos",
      "Calasiao",
      "Dagupan City",
      "Dasol",
      "Infanta",
      "Labrador",
      "Laoac",
      "Lingayen",
      "Mabini",
      "Malasiqui",
      "Manaoag",
      "Mangaldan",
      "Mangatarem",
      "Mapandan",
      "Natividad",
      "Pozorrubio",
      "Rosales",
      "San Carlos City",
      "San Fabian",
      "San Jacinto",
      "San Manuel",
      "San Nicolas",
      "San Quintin",
      "Santa Barbara",
      "Santa Maria",
      "Santo Tomas",
      "Sison",
      "Sual",
      "Tayug",
      "Umingan",
      "Urbiztondo",
      "Urdaneta City",
      "Villasis",
    ],
  },
  {
    province: "Quezon",
    municipalities: [
      "Agdangan",
      "Alabat",
      "Atimonan",
      "Buenavista",
      "Burdeos",
      "Calauag",
      "Candelaria",
      "Catanauan",
      "Dolores",
      "General Luna",
      "General Nakar",
      "Guinayangan",
      "Gumaca",
      "Infanta",
      "Jomalig",
      "Lopez",
      "Lucban",
      "Lucena City",
      "Macalelon",
      "Mauban",
      "Mulanay",
      "Padre Burgos",
      "Pagbilao",
      "Panukulan",
      "Patnanungan",
      "Perez",
      "Pitogo",
      "Plaridel",
      "Polillo",
      "Quezon",
      "Real",
      "Sampaloc",
      "San Andres",
      "San Antonio",
      "San Francisco",
      "San Narciso",
      "Sariaya",
      "Tagkawayan",
      "Tayabas City",
      "Tiaong",
      "Unisan",
    ],
  },
  {
    province: "Quirino",
    municipalities: [
      "Aglipay",
      "Cabarroguis",
      "Diffun",
      "Maddela",
      "Nagtipunan",
      "Saguday",
    ],
  },
  {
    province: "Rizal",
    municipalities: [
      "Angono",
      "Antipolo City",
      "Baras",
      "Binangonan",
      "Cainta",
      "Cardona",
      "Jala-Jala",
      "Morong",
      "Pililla",
      "Rodriguez",
      "San Mateo",
      "Tanay",
      "Taytay",
      "Teresa",
    ],
  },
  {
    province: "Romblon",
    municipalities: [
      "Alcantara",
      "Banton",
      "Cajidiocan",
      "Calatrava",
      "Concepcion",
      "Corcuera",
      "Ferrol",
      "Looc",
      "Magdiwang",
      "Odiongan",
      "Romblon",
      "San Agustin",
      "San Andres",
      "San Fernando",
      "San Jose",
      "Santa Fe",
      "Santa Maria",
    ],
  },
  {
    province: "Samar",
    municipalities: [
      "Almagro",
      "Basey",
      "Calbayog City",
      "Calbiga",
      "Catbalogan City",
      "Daram",
      "Gandara",
      "Hinabangan",
      "Jiabong",
      "Marabut",
      "Matuguinao",
      "Motiong",
      "Pagsanghan",
      "Paranas",
      "Pinabacdao",
      "San Jorge",
      "San Jose de Buan",
      "San Sebastian",
      "Santa Margarita",
      "Santa Rita",
      "Santo Niño",
      "Tagapul-an",
      "Talalora",
      "Tarangnan",
      "Villareal",
      "Zumarraga",
    ],
  },
  {
    province: "Sarangani",
    municipalities: [
      "Alabel",
      "Glan",
      "Kiamba",
      "Maasim",
      "Maitum",
      "Malapatan",
      "Malungon",
    ],
  },
  {
    province: "Siquijor",
    municipalities: [
      "Enrique Villanueva",
      "Larena",
      "Lazi",
      "Maria",
      "San Juan",
      "Siquijor",
    ],
  },
  {
    province: "Sorsogon",
    municipalities: [
      "Barcelona",
      "Bulan",
      "Bulusan",
      "Casiguran",
      "Castilla",
      "Donsol",
      "Gubat",
      "Irosin",
      "Juban",
      "Magallanes",
      "Matnog",
      "Pilar",
      "Prieto Diaz",
      "Santa Magdalena",
      "Sorsogon City",
    ],
  },
  {
    province: "South Cotabato",
    municipalities: [
      "Banga",
      "General Santos City",
      "Koronadal City",
      "Lake Sebu",
      "Norala",
      "Polomolok",
      "Santo Niño",
      "Surallah",
      "T'boli",
      "Tampakan",
      "Tantangan",
      "Tupi",
    ],
  },
  {
    province: "Southern Leyte",
    municipalities: [
      "Anahawan",
      "Bontoc",
      "Hinunangan",
      "Hinundayan",
      "Libagon",
      "Liloan",
      "Macrohon",
      "Malitbog",
      "Padre Burgos",
      "Pintuyan",
      "Saint Bernard",
      "San Francisco",
      "San Juan",
      "San Ricardo",
      "Silago",
      "Sogod",
      "Tomas Oppus",
      "Maasin City",
    ],
  },
  {
    province: "Sultan Kudarat",
    municipalities: [
      "Bagumbayan",
      "Columbio",
      "Esperanza",
      "Isulan",
      "Kalamansig",
      "Lambayong",
      "Lebak",
      "Lutayan",
      "Palimbang",
      "President Quirino",
      "Senator Ninoy Aquino",
      "Tacurong City",
    ],
  },
  {
    province: "Sulu",
    municipalities: [
      "Banguingui",
      "Hadji Panglima Tahil",
      "Indanan",
      "Jolo",
      "Kalingalan Caluang",
      "Lugus",
      "Luuk",
      "Maimbung",
      "Old Panamao",
      "Omar",
      "Pandami",
      "Panglima Estino",
      "Pangutaran",
      "Parang",
      "Pata",
      "Patikul",
      "Siasi",
      "Talipao",
      "Tapul",
    ],
  },
  {
    province: "Surigao del Norte",
    municipalities: [
      "Alegria",
      "Bacuag",
      "Burgos",
      "Claver",
      "Dapa",
      "Del Carmen",
      "General Luna",
      "Gigaquit",
      "Mainit",
      "Malimono",
      "Pilar",
      "Placer",
      "San Benito",
      "San Francisco",
      "San Isidro",
      "Santa Monica",
      "Sison",
      "Socorro",
      "Surigao City",
      "Tagana-an",
      "Tubod",
    ],
  },
  {
    province: "Surigao del Sur",
    municipalities: [
      "Barobo",
      "Bayabas",
      "Bislig City",
      "Cagwait",
      "Cantilan",
      "Carmen",
      "Carrascal",
      "Cortes",
      "Hinatuan",
      "Lanuza",
      "Lianga",
      "Lingig",
      "Madrid",
      "Marihatag",
      "San Agustin",
      "San Miguel",
      "Tagbina",
      "Tago",
      "Tandag City",
    ],
  },
  {
    province: "Tarlac",
    municipalities: [
      "Anao",
      "Bamban",
      "Camiling",
      "Capas",
      "Concepcion",
      "Gerona",
      "La Paz",
      "Mayantoc",
      "Moncada",
      "Paniqui",
      "Pura",
      "Ramos",
      "San Clemente",
      "San Jose",
      "San Manuel",
      "Santa Ignacia",
      "Tarlac City",
      "Victoria",
    ],
  },
  {
    province: "Tawi-Tawi",
    municipalities: [
      "Bongao",
      "Languyan",
      "Mapun",
      "Panglima Sugala",
      "Sapa-Sapa",
      "Sibutu",
      "Simunul",
      "Sitangkai",
      "South Ubian",
      "Tandubas",
      "Turtle Islands",
    ],
  },
  {
    province: "Zambales",
    municipalities: [
      "Botolan",
      "Cabangan",
      "Candelaria",
      "Castillejos",
      "Iba",
      "Masinloc",
      "Olongapo City",
      "Palauig",
      "San Antonio",
      "San Felipe",
      "San Marcelino",
      "San Narciso",
      "Santa Cruz",
      "Subic",
    ],
  },
  {
    province: "Zamboanga del Norte",
    municipalities: [
      "Bacungan",
      "Baliguian",
      "Dapitan City",
      "Dipolog City",
      "Godod",
      "Gutalac",
      "Jose Dalman",
      "Kalawit",
      "Katipunan",
      "La Libertad",
      "Labason",
      "Leon B. Postigo",
      "Liloy",
      "Manukan",
      "Mutia",
      "Piñan",
      "Polanco",
      "Pres. Manuel A. Roxas",
      "Rizal",
      "Salug",
      "Sergio Osmeña Sr.",
      "Siayan",
      "Sibuco",
      "Sibutad",
      "Sindangan",
      "Siocon",
      "Sirawai",
      "Tampilisan",
    ],
  },
  {
    province: "Zamboanga del Sur",
    municipalities: [
      "Aurora",
      "Bayog",
      "Dimataling",
      "Dinas",
      "Dumalinao",
      "Dumingag",
      "Guipos",
      "Josefina",
      "Kumalarang",
      "Labangan",
      "Lakewood",
      "Lapuyan",
      "Mahayag",
      "Margosatubig",
      "Midsalip",
      "Molave",
      "Pagadian City",
      "Pitogo",
      "Ramon Magsaysay",
      "San Miguel",
      "San Pablo",
      "Sominot",
      "Tabina",
      "Tambulig",
      "Tigbao",
      "Tukuran",
      "Vincenzo A. Sagun",
      "Zamboanga City",
    ],
  },
  {
    province: "Zamboanga Sibugay",
    municipalities: [
      "Alicia",
      "Buug",
      "Diplahan",
      "Imelda",
      "Ipil",
      "Kabasalan",
      "Mabuhay",
      "Malangas",
      "Naga",
      "Olutanga",
      "Payao",
      "Roseller Lim",
      "Siay",
      "Talusan",
      "Titay",
      "Tungawan",
    ],
  },
];

// Helper functions
export const getRegions = (): string[] => {
  return [
    "Ilocos Region",
    "Cagayan Valley",
    "Central Luzon",
    "NCR",
    "CALABARZON",
    "MIMAROPA",
    "Bicol",
    "Western Visayas",
    "Central Visayas",
    "Eastern Visayas",
    "Negros Island",
    "Zamboanga Peninsula",
    "Northern Mindanao",
    "Davao Region",
    "Soccsksargen",
    "Caraga",
    "CAR",
    "BARMM",
  ];
};

// Region to Province mapping
const regionProvinceMap: { [key: string]: string[] } = {
  NCR: ["Metro Manila"],
  CAR: ["Abra", "Apayao", "Benguet", "Ifugao", "Kalinga", "Mountain Province"],
  "Ilocos Region": ["Ilocos Norte", "Ilocos Sur", "La Union", "Pangasinan"],
  "Cagayan Valley": [
    "Batanes",
    "Cagayan",
    "Isabela",
    "Nueva Vizcaya",
    "Quirino",
  ],
  "Central Luzon": [
    "Aurora",
    "Bataan",
    "Bulacan",
    "Nueva Ecija",
    "Pampanga",
    "Tarlac",
    "Zambales",
  ],
  CALABARZON: ["Batangas", "Cavite", "Laguna", "Quezon", "Rizal"],
  MIMAROPA: [
    "Marinduque",
    "Occidental Mindoro",
    "Oriental Mindoro",
    "Palawan",
    "Romblon",
  ],
  Bicol: [
    "Albay",
    "Camarines Norte",
    "Camarines Sur",
    "Catanduanes",
    "Masbate",
    "Sorsogon",
  ],
  "Western Visayas": [
    "Aklan",
    "Antique",
    "Capiz",
    "Guimaras",
    "Iloilo",
    "Negros Occidental",
  ],
  "Central Visayas": ["Bohol", "Cebu", "Negros Oriental", "Siquijor"],
  "Eastern Visayas": [
    "Biliran",
    "Eastern Samar",
    "Leyte",
    "Northern Samar",
    "Samar",
    "Southern Leyte",
  ],
  "Negros Island": ["Negros Occidental", "Negros Oriental"],
  "Zamboanga Peninsula": [
    "Zamboanga del Norte",
    "Zamboanga del Sur",
    "Zamboanga Sibugay",
  ],
  "Northern Mindanao": [
    "Bukidnon",
    "Camiguin",
    "Lanao del Norte",
    "Misamis Occidental",
    "Misamis Oriental",
  ],
  "Davao Region": [
    "Davao de Oro (Compostela Valley)",
    "Davao del Norte",
    "Davao del Sur",
    "Davao Occidental",
    "Davao Oriental",
  ],
  Soccsksargen: ["Cotabato", "Sarangani", "South Cotabato", "Sultan Kudarat"],
  Caraga: [
    "Agusan del Norte",
    "Agusan del Sur",
    "Dinagat Islands",
    "Surigao del Norte",
    "Surigao del Sur",
  ],
  BARMM: [
    "Basilan",
    "Lanao del Sur",
    "Maguindanao del Norte",
    "Maguindanao del Sur",
    "Sulu",
    "Tawi-Tawi",
  ],
};

export const getProvincesByRegion = (region: string): string[] => {
  if (region === "All Regions" || !region) {
    return provinces.map((p) => p.province);
  }
  return regionProvinceMap[region] || [];
};

export const getMunicipalitiesByProvince = (province: string): string[] => {
  const foundProvince = provinces.find((p) => p.province === province);
  return foundProvince ? foundProvince.municipalities : [];
};

export const getAllProvinces = (): string[] => {
  return provinces.map((p) => p.province);
};
