"use client";
import React, { useState } from "react";
import { Download } from "lucide-react";

const FranchiseeDataProcessor = () => {
  const [processing, setProcessing] = useState(false);

  const processData = () => {
    // Parse and extract unique franchisees
    const franchiseeMap = new Map();

    // Updated and validated rawData based on your list
    const rawData = [
      {
        id: 1,
        name: "MICHAELANGELO AMBAYEC CORONADO",
        region: "CALABARZON",
        birthdate: "May 2, 1987",
        tin: "291-621-542",
        email: "tinacoronado24@gmail.com",
        mobile: "9178869540",
        address: "SAN LORENZO PLACE CONDO EDSA CORNER PASONG TAMO MAKATI CITY",
        birthplace: "",
        regDate: "March 23, 2023",
      },
      {
        id: 2,
        name: "MA. TERESA LOZANO VEROY",
        region: "",
        birthdate: "September 16, 1976",
        tin: "",
        email: "tessa_lozano@yahoo.com",
        mobile: "9064400220",
        address: "66 JOSE ABAD SANTOS ST. HEROES HILLS QUEZON CITY",
        birthplace: "",
        regDate: "March 27, 2023",
      },
      {
        id: 3,
        name: "KENNETH JOHN AVILA DE GUIA",
        region: "",
        birthdate: "",
        tin: "",
        email: "kjadeguia@gmail.com",
        mobile: "9175863986",
        address: "",
        birthplace: "",
        regDate: "April 17, 2023",
      },
      {
        id: 4,
        name: "DANIEL FELIX ALVERO BELEN",
        region: "CALABARZON",
        birthdate: "July 19, 1985",
        tin: "",
        email: "dfabelen@yahoo.com",
        mobile: "9177034927",
        address:
          "1523 ST. FRANCIS AVE. FARCONVILLE SUBD. SAN PABLO CITY LAGUNA",
        birthplace: "",
        regDate: "April 15, 2023",
      },
      {
        id: 5,
        name: "RICARDO CARLO RAGUDO NACA",
        region: "NCR",
        birthdate: "March 4, 1989",
        tin: "",
        email: "carloncnr@yahoo.com",
        mobile: "9177926255",
        address:
          "UNIT 2A THE WACK-WACK PLACE LEE ST. BRGY. ADDITION HILLS MANDALUYONG CITY",
        birthplace: "",
        regDate: "April 30, 2023",
      },
      {
        id: 6,
        name: "ALLAN TADINA QUILATAN",
        region: "CALABARZON",
        birthdate: "September 3,1975",
        tin: "190-831-341-00005",
        email: "quilatan.allan@gmail.com",
        mobile: "9989769016",
        address: "108 P. CRUZ ST. BRGY. SAN JOSE MANDALUYONG CITY",
        birthplace: "",
        regDate: "April 17, 2023",
      },
      {
        id: 7,
        name: "ANNA RUTH DIZON FONTANILLA",
        region: "NCR",
        birthdate: "March 11, 1991",
        tin: "408-991-526",
        email: "ruthfontanilla0311@gmail.com",
        mobile: "9156279154",
        address: "BLK 1 LOT 23 VAA HOMES 3 NAGA RD. PULANG LUPA LAS PIÑAS",
        birthplace: "",
        regDate: "May 5, 2023",
      },
      {
        id: 8,
        name: "MARGIELAINE QUITORIANO ABRINA",
        region: "NCR",
        birthdate: "September 1, 1974",
        tin: "652-166-339-00001/652-166-339-00000",
        email: "margielaine.abrina@gmail.com",
        mobile: "9985785083",
        address: "3 ESTEBAN ABADA ST. LOYOLA HEIGHTS QUEZON CITY",
        birthplace: "",
        regDate: "May 19, 2023",
      },
      {
        id: 9,
        name: "NEIL PATRICK PINEDA NUNAG",
        region: "CENTRAL LUZON",
        birthdate: "July 19, 1993",
        tin: "",
        email: "jo.antigo08@gmail.com",
        mobile: "9190078231",
        address:
          "1865 VELASQUEZ BLVD. SUNSET VALLEY HOMES ANGELES CITY PAMPANGA",
        birthplace: "",
        regDate: "May 31, 2023",
      },
      {
        id: 10,
        name: "RENEE BOY VILLANUEVA GUNITA",
        region: "",
        birthdate: "",
        tin: "",
        email: "rvgunita@yahoo.com",
        mobile: "9175231305",
        address: "",
        birthplace: "",
        regDate: "June 8, 2023",
      },
      {
        id: 11,
        name: "MENCHIE TALION VILLANUEVA",
        region: "NCR",
        birthdate: "January 12, 1980",
        tin: "",
        email: "villanuevamenchie@gmail.com",
        mobile: "9212060164",
        address: "BLK A8 LOT 15 BRGY. SAN SIMON DASMARIÑAS CAVITE",
        birthplace: "",
        regDate: "July 20, 2023",
      },
      {
        id: 12,
        name: "PATRICIA RENEE GRAGEDA MOLINA",
        region: "CENTRAL LUZON",
        birthdate: "October 23, 1992",
        tin: "",
        email: "hatchspace.design@gmail.com",
        mobile: "9178881206",
        address: "7 IFUGAO ST. VILLA GLORIA SUBD. ANGELES CITY PAMPANGA",
        birthplace: "",
        regDate: "July 10, 2023",
      },
      {
        id: 13,
        name: "SHERYLOU ANG LIM",
        region: "",
        birthdate: "August 17, 1979",
        tin: "",
        email: "sherylou.lim@gmail.com",
        mobile: "9178660817",
        address: "46 E ALBANY ST. CUBAO SILANGAN QUEZON CITY",
        birthplace: "",
        regDate: "July 16, 2023",
      },
      {
        id: 14,
        name: "REAH LIO CASTRO",
        region: "NCR",
        birthdate: "April 13, 1980",
        tin: "",
        email: "reah.lio@gmail.com",
        mobile: "9175389910",
        address: "U304 T2 ONE OCHARD RD. COND EASTWOOD LIBIS QUEZON CITY",
        birthplace: "",
        regDate: "August 4, 2023",
      },
      {
        id: 15,
        name: "JAMAYNE CASTILLO TAN",
        region: "CENTRAL LUZON",
        birthdate: "May 4, 1992",
        tin: "",
        email: "jamctan@yahoo.com",
        mobile: "9171125388",
        address: "128 RUBY ST. PLARIDEL HEIGHTS SUBD. SANTIAGO CITY ISABELA",
        birthplace: "",
        regDate: "August 10, 2023",
      },
      {
        id: 16,
        name: "MIGUEL PAOLO TICSAY PAZ",
        region: "CALABARZON",
        birthdate: "",
        tin: "",
        email: "miguelpaz1986@gmail.com",
        mobile: "",
        address: "",
        birthplace: "",
        regDate: "August 10, 2023",
      },
      {
        id: 17,
        name: "MICHELLE SIRIBAN NARCISO",
        region: "CALABARZON",
        birthdate: "July 12, 1981",
        tin: "",
        email: "michelle.narciso@me.com",
        mobile: "9276818800",
        address: "2 M DELA FUENTE ST. BF RESORT VILL TALON DOS LAS PIÑAS CITY",
        birthplace: "",
        regDate: "August 25, 2023",
      },
      {
        id: 18,
        name: "JAMES RICHARD EUGENIO GUEVARRA",
        region: "CALABARZON",
        birthdate: "February 10, 1991",
        tin: "",
        email: "jamesrichardguevarra@yahoo.com",
        mobile: "9236039258",
        address:
          "BLK 28 LOT 2,3,4 DAFFODILS ST. PH2 VISTA VERDE SOUTH EXECUTIVE VILLAGE MAMBOG 3 BACOOR CITY CAVITE",
        birthplace: "",
        regDate: "August 29, 2023",
      },
      {
        id: 19,
        name: "JOANNA MARIE ANTIGO NUNAG",
        region: "CENTRAL LUZON",
        birthdate: "May 4, 1993",
        tin: "",
        email: "jo.antigo08@gmail.com",
        mobile: "9190044459",
        address:
          "1865 VELASQUEZ BLVD. SUNSET VALLEY HOMES ANGELES CITY PAMPANGA",
        birthplace: "",
        regDate: "September 18, 2023",
      },
      {
        id: 20,
        name: "CECILIA SY DELA ROSA",
        region: "NCR",
        birthdate: "September 8, 1983",
        tin: "",
        email: "cecil_sy17@yahoo.com",
        mobile: "9173247955",
        address: "22 A CARCON ST. GREENHEIGHTS VILLAGE PARAÑAQUE",
        birthplace: "",
        regDate: "September 18, 2023",
      },
      {
        id: 21,
        name: "RIANNE GENESIS BERMUDO PADDEN",
        region: "CENTRAL LUZON",
        birthdate: "June 3, 1986",
        tin: "",
        email: "rianne_genesis@yahoo.com.ph",
        mobile: "9985710603",
        address: "B39 32 BALTIMORE ST. TIMOG RESIDENCE ANGELES CITY PAMPANGA",
        birthplace: "",
        regDate: "September 25, 2023",
      },
      {
        id: 22,
        name: "RIZA MARQUEZ PLANTA",
        region: "OTHERS",
        birthdate: "June 2, 1976",
        tin: "",
        email: "rizmarquez@gmail.com",
        mobile: "9178540170",
        address:
          "1003 TOWER F THE GROVE BY ROCKWELL E. RODRIGUEZ JR. AVENUE BRGY. UGONG PASIG CITY",
        birthplace: "",
        regDate: "November 6, 2023",
      },
      {
        id: 23,
        name: "FRANCIS PACIENTE JAENA JR.",
        region: "CALABARZON",
        birthdate: "November 12, 1976",
        tin: "",
        email: "fjaena@gmail.com",
        mobile: "9171149231",
        address:
          "PHASE 3 BLK 37 LOT 14-B THE GENTRI HEIGHTS MANGGAHAN GEN. TRIAS CAVITE",
        birthplace: "",
        regDate: "March 19, 2024",
      },
      {
        id: 24,
        name: "IAN DOMINIC LIM LU CHIU",
        region: "NCR",
        birthdate: "",
        tin: "",
        email: "ian5112017@gmail.com",
        mobile: "",
        address: "",
        birthplace: "",
        regDate: "December 21, 2023",
      },
      {
        id: 25,
        name: "NANCY RIVERA QUINDOY",
        region: "",
        birthdate: "",
        tin: "",
        email: "",
        mobile: "9561288371",
        address: "",
        birthplace: "",
        regDate: "January 3, 2024",
      },
      {
        id: 26,
        name: "FRANCE MARTINE LOVENDINO BUENO",
        region: "",
        birthdate: "April 28, 1993",
        tin: "",
        email: "hirefrancemartinebueno@gmail.com",
        mobile: "9214385347",
        address: "#314 TOWER E SEA RESIDENCES PASAY CITY",
        birthplace: "",
        regDate: "January 4, 2024",
      },
      {
        id: 27,
        name: "JANELLE ANN LIM DE JESUS",
        region: "",
        birthdate: "April 8, 1991",
        tin: "",
        email: "janelleldejesus@gmail.com",
        mobile: "9175042732",
        address: "20 MACOPA ST. BRGY. ST. PETER QUEZON CITY",
        birthplace: "",
        regDate: "January 14, 2024",
      },
      {
        id: 28,
        name: "KATHERINE ANN YUZON AINZA",
        region: "NCR",
        birthdate: "April 7, 1979",
        tin: "",
        email: "kay.ainza@gmail.com",
        mobile: "9178924779",
        address: "50 AUBURN ST. NORTH FAIRVIEW PARK QUEZON CITY",
        birthplace: "",
        regDate: "January 17, 2024",
      },
      {
        id: 29,
        name: "JHENDIE MAFORIE DIZON BERNABE",
        region: "CENTRAL LUZON",
        birthdate: "September 2, 1986",
        tin: "500-311-419",
        email: "Jeniefercastro@yahoo.com",
        mobile: "9395218528",
        address: "PHASE 3 BLK 1 LOT 6 CAMELLA HOMES MATUNGAO BULACAN",
        birthplace: "",
        regDate: "January 20, 2024",
      },
      {
        id: 30,
        name: "ANNA LOURDES VELASCO MANGIO",
        region: "CENTRAL LUZON",
        birthdate: "May 6, 1977",
        tin: "202-479-489",
        email: "annavmangio@gmail.com",
        mobile: "9178971977",
        address: "241 SANTOLAN ROAD QUEZON CITY",
        birthplace: "",
        regDate: "January 24, 2024",
      },
      {
        id: 31,
        name: "BENJO QUIÑONERO CADUNGAN",
        region: "NCR",
        birthdate: "May 20, 1975",
        tin: "198-751-241",
        email: "bqcadungan@gmail.com",
        mobile: "9177915998",
        address: "61B BAUTISTA ST. CJVAB PASAY CITY",
        birthplace: "",
        regDate: "January 25, 2024",
      },
      {
        id: 32,
        name: "KATE MILLICENT ONG LEE",
        region: "",
        birthdate: "February 4, 1996",
        tin: "",
        email: "kate1millicent@gmail.com",
        mobile: "9774655859",
        address: "10 PURDUE ST. SAN JUAN CITY METRO MANILA",
        birthplace: "",
        regDate: "February 16, 2024",
      },
      {
        id: 33,
        name: "JASON DECENA GO",
        region: "NCR",
        birthdate: "November 9, 1992",
        tin: "",
        email: "jasondgo09@gmail.com",
        mobile: "9175189891",
        address: "9L LINCOLN TOWER ROCKWELL MAKATI CITY",
        birthplace: "",
        regDate: "February 17, 2024",
      },
      {
        id: 34,
        name: "EDRICK ALLEN ARIAS CATUNGAL",
        region: "NCR",
        birthdate: "June 9, 1994",
        tin: "648-962-573",
        email: "edrickcatungal@gmail.com",
        mobile: "9178878897",
        address: "738 ONGPIN ST. BINONDO MANILA",
        birthplace: "",
        regDate: "February 26, 2024",
      },
      {
        id: 35,
        name: "PETER JEROME NATIVIDAD SEROMINES",
        region: "NCR",
        birthdate: "November 14, 1992",
        tin: "284-336-273",
        email: "pjseromines@gmail.com",
        mobile: "9179043804",
        address: "372 SAN SEBASTIAN HILLS TANAUAN CITY BATANGAS",
        birthplace: "",
        regDate: "February 29, 2024",
      },
      {
        id: 36,
        name: "PAULINE SANTOS LUCERO",
        region: "NCR",
        birthdate: "March 16, 1993",
        tin: "",
        email: "lucerogoc@gmail.com",
        mobile: "",
        address: "83 CHESTNUT ST. SOUTHRIDGE ESTATES TAGAYTAY CITY",
        birthplace: "",
        regDate: "March 6, 2024",
      },
      {
        id: 37,
        name: "MIGUEL JUAN MARQUEZ VELASCO",
        region: "",
        birthdate: "",
        tin: "",
        email: "mjmvelasco1989@yahoo.com",
        mobile: "9176287686",
        address: "",
        birthplace: "",
        regDate: "March 9, 2024",
      },
      {
        id: 38,
        name: "REYNALDO ATANACIO CABANEZAS JR.",
        region: "",
        birthdate: "",
        tin: "",
        email: "rei.cabanezas@gmail.com",
        mobile: "9992238257",
        address: "",
        birthplace: "",
        regDate: "March 27, 2024",
      },
      {
        id: 39,
        name: "MARILOU CALMA NAVARRO",
        region: "CALABARZON",
        birthdate: "January 21, 1988",
        tin: "653-419-299",
        email: "navarromariloucalma@gmail.com",
        mobile: "9977059773",
        address: "BLK 5 LOT 4 MELTON PLACE BRGY. TAGPOS BINANGONAN RIZAL",
        birthplace: "",
        regDate: "May 26, 2024",
      },
      {
        id: 40,
        name: "JEROME JAVIER TUAÑO GUECO",
        region: "CENTRAL LUZON",
        birthdate: "February 29, 1976",
        tin: "",
        email: "rianne_genesis@yahoo.com.ph",
        mobile: "9985710603",
        address: "39-32 BALTIMORE ST. TIMOG RESIDENCE",
        birthplace: "",
        regDate: "June 3, 2024",
      },
      {
        id: 41,
        name: "ROCHELLE CRUZ GRAGASIN",
        region: "CENTRAL LUZON",
        birthdate: "October 2, 1979",
        tin: "",
        email: "aselcruz@yahoo.com",
        mobile: "9399239136",
        address: "#44 DOLLAR ST. URBAN BLISS BARANGKA MARIKINA CITY",
        birthplace: "",
        regDate: "June 14, 2024",
      },
      {
        id: 42,
        name: "MIKKO SALCEDO ARROZAL",
        region: "",
        birthdate: "June 14, 1975",
        tin: "",
        email: "mikko.optionb@gmail.com",
        mobile: "9257368377",
        address: "",
        birthplace: "",
        regDate: "June 24, 2024",
      },
      {
        id: 43,
        name: "MARIO ANGELO DIZON AFABLE",
        region: "NCR",
        birthdate: "February 7, 1983",
        tin: "279-986-444",
        email: "mario.a.afable@gmail.com",
        mobile: "9178987731",
        address: "59 MAGINHAWA ST. UP VILLAGE QUEZON CITY",
        birthplace: "",
        regDate: "June 30, 2024",
      },
      {
        id: 44,
        name: "JOSE EDUARDO ROXAS BELEN",
        region: "",
        birthdate: "June 12, 1984",
        tin: "",
        email: "jedbelen@gmail.com",
        mobile: "9150578715",
        address: "118 A UPPER LIWANAG LUAKAN BAGUIO CITY",
        birthplace: "",
        regDate: "July 10, 2024",
      },
      {
        id: 45,
        name: "ANNALYN DIZON DELAVIN",
        region: "",
        birthdate: "February 6, 1980",
        tin: "",
        email: "annedelavin6@gmail.com",
        mobile: "9178112663",
        address:
          "708 SAN FRANCISCO GARDENS CONDO CYIC BONI AVE. MANDALUYONG CITY",
        birthplace: "",
        regDate: "July 13, 2024",
      },
      {
        id: 46,
        name: "RACHELLE CRUZ RAMOS",
        region: "NCR",
        birthdate: "October 15, 1980",
        tin: "218-204-977",
        email: "rwl.rralbadri@yahoo.com",
        mobile: "9175258777",
        address:
          "UNIT 19A MOSAIC TOWER TRASIERRA ST. LEGAZPI VILLAGE MAKATI CITY",
        birthplace: "",
        regDate: "July 26, 2024",
      },
      {
        id: 47,
        name: "RICHIELDA GABUCOS LAO",
        region: "",
        birthdate: "August 11, 1978",
        tin: "",
        email: "richielda_c@yahoo.com",
        mobile: "9176276557",
        address: "33 KIRKWOOD COURT SOUTH HILLS SUBD. TISA CEBU CITY",
        birthplace: "",
        regDate: "July 23, 2024",
      },
      {
        id: 48,
        name: "DOMINIQUE CABRAL RAMOS",
        region: "",
        birthdate: "September 17, 1997",
        tin: "",
        email: "ramosdominquecabral@gmail.com",
        mobile: "9772886355",
        address: "UNIT 01 ORANGE APARTMENT EARTH ST. TUMAGA ZAMBOANGA CITY",
        birthplace: "",
        regDate: "July 25, 2024",
      },
      {
        id: 49,
        name: "JHOANNA FREDERICKA HICETA GATON",
        region: "NCR",
        birthdate: "March 13, 1988",
        tin: "271-272-666",
        email: "jfhiceta@gmail.com",
        mobile: "9177057315",
        address:
          "44 YELLOWBELL ST. DOÑA MANUELA SUBD. PAMPLONA 3 LAS PIÑAS CITY",
        birthplace: "",
        regDate: "July 31, 2024",
      },
      {
        id: 50,
        name: "KATRINA MARIE DE LEON ERMINO",
        region: "CALABARZON",
        birthdate: "December 19, 1999",
        tin: "",
        email: "joelandkat21@gmail.com",
        mobile: "9173195638",
        address: "72 EVANGELISTA ST. KAINAIN BACOOR CITY CAVITE",
        birthplace: "",
        regDate: "August 29, 2024",
      },
      {
        id: 51,
        name: "JENELA MAY TUGUINAY CACHERO",
        region: "CENTRAL LUZON",
        birthdate: "June 16, 1997",
        tin: "501-946-638",
        email: "jmtuguinay1@gmail.com",
        mobile: "9997126939",
        address: "#29 LARAYA ST. MIDDLE QUEZON HILL BAGUIO CITY",
        birthplace: "",
        regDate: "September 9, 2024",
      },
      {
        id: 52,
        name: "ANNABEL GALANG BUSTILLO",
        region: "",
        birthdate: "October 17, 1980",
        tin: "",
        email: "agbustillo@yahoo.com",
        mobile: "9178393330",
        address: "1852 YAKAL ST. STA. CRUZ MANILA",
        birthplace: "",
        regDate: "September 30, 2024",
      },
      {
        id: 53,
        name: "JOCELYN CALINA PAGODPOD",
        region: "NCR",
        birthdate: "September 26, 1977",
        tin: "618-571-828",
        email: "jocelynpagodpod@gmail.com",
        mobile: "9983912661",
        address: "19 YELLOWBELL ST. POTRERO MALABON",
        birthplace: "",
        regDate: "October 8, 2024",
      },
      {
        id: 54,
        name: "JOSEPH SAYAT DE LA CUESTA",
        region: "",
        birthdate: "November 2, 1976",
        tin: "215-918-584",
        email: "jeps.icloud@icloud.com",
        mobile: "9175954707",
        address: "LOT 2 BLK 3 MARICHI SUBD. SARIAYA QUEZON",
        birthplace: "",
        regDate: "October 7, 2024",
      },
      {
        id: 55,
        name: "EMJOYCE ANN DANGANAN DE GUZMAN",
        region: "",
        birthdate: "June 10, 2000",
        tin: "",
        email: "eyzianne@gmail.com",
        mobile: "9620981286",
        address: "",
        birthplace: "",
        regDate: "October 10, 2024",
      },
      {
        id: 56,
        name: "LAARNIE LUBRICO CHUA",
        region: "NCR",
        birthdate: "July 27, 1971",
        tin: "",
        email: "arnichua@gmail.com",
        mobile: "9175329759",
        address: "21 WARBLER ST. GREENMEADOWS QUEZON CITY",
        birthplace: "",
        regDate: "October 10, 2024",
      },
      {
        id: 57,
        name: "PATRICK HUI YEUNG",
        region: "NCR",
        birthdate: "January 17, 1972",
        tin: "",
        email: "steaming.cup18@gmail.com",
        mobile: "9176306664",
        address: "",
        birthplace: "",
        regDate: "October 18, 2024",
      },
      {
        id: 58,
        name: "AILEN MARYLOU SILVIO BIGAY",
        region: "",
        birthdate: "August 24, 1982",
        tin: "",
        email: "ailenbigay@gmail.com",
        mobile: "9065595354",
        address: "",
        birthplace: "",
        regDate: "October 19, 2024",
      },
      {
        id: 59,
        name: "ELIZA RAZON CAPULONG",
        region: "NCR",
        birthdate: "September 7, 1974",
        tin: "",
        email: "josephfernandez2494@gmail.com",
        mobile: "9565865045",
        address: "155 J.P RIZAL CALUMPANG CALUMPIT BULACAN",
        birthplace: "",
        regDate: "October 21, 2024",
      },
      {
        id: 60,
        name: "KATHRINA HAM YU",
        region: "NCR",
        birthdate: "July 29, 1977",
        tin: "010-867-394",
        email: "kathrina729@gmail.com",
        mobile: "9175888528",
        address:
          "UNIT 33B TOWER 4 SAN LORENZO PLACE CONDOMINIUM EDS COR. CHINO ROCES AVE. BANGKAL MAKATI CITY",
        birthplace: "",
        regDate: "October 28, 2024",
      },
      {
        id: 61,
        name: "RICHMOND KEENE RUFIN TANO",
        region: "OTHERS",
        birthdate: "March 24, 1990",
        tin: "",
        email: "richmondkeenetano@yahoo.com",
        mobile: "9455988765",
        address: "",
        birthplace: "",
        regDate: "October 23, 2024",
      },
      {
        id: 62,
        name: "BASIL-JACOB DEL PILAR REYNO",
        region: "",
        birthdate: "March 15, 1993",
        tin: "",
        email: "basilreyno@gmail.com",
        mobile: "9155147374",
        address: "",
        birthplace: "",
        regDate: "November 11, 2024",
      },
      {
        id: 63,
        name: "MICHAEL CARINO MARCIAL",
        region: "CENTRAL LUZON",
        birthdate: "August 13, 1998",
        tin: "",
        email: "michaelmarcial888@gmail.com",
        mobile: "9488188606",
        address: "",
        birthplace: "",
        regDate: "November 13, 2024",
      },
      {
        id: 64,
        name: "RAMALLAH DAGALANGIT BALT",
        region: "",
        birthdate: "October 5, 2000",
        tin: "",
        email: "baltreema@gmail.com",
        mobile: "92798880016",
        address: "",
        birthplace: "",
        regDate: "November 15, 2024",
      },
      {
        id: 65,
        name: "ALYANNA BALOLOT SAMPIANO",
        region: "NCR",
        birthdate: "March 4, 2002",
        tin: "350-576-813",
        email: "alyannasampiano@gmail.com",
        mobile: "9234215770",
        address: "",
        birthplace: "",
        regDate: "November 20, 2024",
      },
      {
        id: 66,
        name: "MARLON POPIOCO SALVADOR",
        region: "",
        birthdate: "January 2, 1985",
        tin: "",
        email: "marlonpsalvador@gmail.com",
        mobile: "9778410909",
        address:
          "BLK 4 LOT 16 MT. ELBRUS ST. RICHDALE SUBD. BRGY. STA. CRUZ ANTIPOLO CITY",
        birthplace: "",
        regDate: "November 22, 2024",
      },
      {
        id: 67,
        name: "JEZZA-LYN BALISCO OLLETA",
        region: "NCR",
        birthdate: "October 3, 1989",
        tin: "331-399-054",
        email: "azzejolleta_132803@yahoo.com",
        mobile: "9605426719",
        address:
          "BLK 5 LOT 1 J HERNANDEZ ST. SAN ANTONIO VALLEY 7 PULANG LUPA 2 LAS PIÑAS CITY",
        birthplace: "",
        regDate: "November 27, 2024",
      },
      {
        id: 68,
        name: "MICCA ANDREA BAUTISTA ORQUIZA",
        region: "CENTRAL LUZON",
        birthdate: "April 26, 1992",
        tin: "455-432-451",
        email: "ar.miccaandreaorquiza@gmail.com",
        mobile: "9088966965",
        address: "PUROK 8 DAMPAY AMUNGAN IBA ZAMBALES",
        birthplace: "",
        regDate: "December 5, 2024",
      },
      {
        id: 69,
        name: "JHOSHUA DENNISE TAN MARIANO",
        region: "CALABARZON",
        birthdate: "",
        tin: "636-358-548",
        email: "",
        mobile: "",
        address: "",
        birthplace: "",
        regDate: "December 7, 2024",
      },
      {
        id: 70,
        name: "SOCORRO REYES MERCADO",
        region: "NCR",
        birthdate: "September 11, 1968",
        tin: "",
        email: "corry.mercado11@gmail.com",
        mobile: "9985930682/9610187201",
        address: "LOT 8 D1 - A DON SEGUNDO ST. BRGY. TALIPAPA QUEZON CITY",
        birthplace: "",
        regDate: "December 26, 2024",
      },
      {
        id: 71,
        name: "DENNIS CRISTOBAL SABALLA MANGOBA",
        region: "CENTRAL LUZON",
        birthdate: "November 2, 1971",
        tin: "270-695-136",
        email: "drdennism@icloud.com",
        mobile: "9228957070",
        address: "356 F. ESTRELLA ST. SANTO ROSARIO MALOLOS BULACAN",
        birthplace: "",
        regDate: "December 26, 2024",
      },
      {
        id: 72,
        name: "GENE ROBERT MIRANDA GUIAO",
        region: "CENTRAL LUZON",
        birthdate: "November 20, 1988",
        tin: "418-920-395",
        email: "gene_guiao1@yahoo.com",
        mobile: "9190840991",
        address:
          "B44 L12 ARANDA DRIVE HOLY ANGEL VILLAGE PHASE 4 TELABASTAGAN SAN FERNANDO PAMPANGA",
        birthplace: "",
        regDate: "December 27, 2024",
      },
      {
        id: 73,
        name: "MARJORIE LEYNES CANTANERO",
        region: "OTHERS",
        birthdate: "October 28, 1994",
        tin: "",
        email: "marjorielcantanero@gmail.com",
        mobile: "971508588951",
        address: "PARAÑAQUE",
        birthplace: "",
        regDate: "December 28, 2024",
      },
      {
        id: 74,
        name: "LENDY DELA CRUZ SEBASTIAN",
        region: "NCR",
        birthdate: "May 6, 2003",
        tin: "660-175-092",
        email: "lendysebastian2003@gmail.com",
        mobile: "9304372075",
        address: "POBLACION PULILAN BULACAN",
        birthplace: "",
        regDate: "December 30, 2024",
      },
      {
        id: 75,
        name: "CEDRIC MALVIN VALDEZ CHAN",
        region: "OTHERS",
        birthdate: "November 8, 1997",
        tin: "711-301-447",
        email: "cedychan08@gmail.com",
        mobile: "9177947540",
        address: "ALWANA VILLAGE CUGMAN CAGAYAN DE ORO CITY MISAMIS ORIENTAL",
        birthplace: "",
        regDate: "January 3, 2025",
      },
      {
        id: 76,
        name: "PHILIP VALERO BELEY",
        region: "",
        birthdate: "May 26, 1958",
        tin: "",
        email: "pvbeley@gmail.com",
        mobile: "9177998102",
        address: "22 - 4 EGYPT ST. BETTER LIVING PARAÑAQUE CITY",
        birthplace: "",
        regDate: "December 18, 2024",
      },
      {
        id: 77,
        name: "MARK ANTHONY GERONA TAN",
        region: "OTHERS",
        birthdate: "August 4, 1992",
        tin: "406-365-188",
        email: "macgt4@gmail.com",
        mobile: "9935368537",
        address:
          "#28 OLD ROYAL OBSERVATORY ST. IMPERIAL RIDGEVIEW SUBD. LEGAZPI CITY ALBAY",
        birthplace: "",
        regDate: "January 13, 2025",
      },
      {
        id: 78,
        name: "DONNALYN BARTOLOME",
        region: "NCR",
        birthdate: "July 9, 1994",
        tin: "436-796-854",
        email: "hiredonnalynbartolome@gmail.com",
        mobile: "9263105745/9165003173",
        address: "79 NAZARETH MULTINATIONAL VILLAGE PARAÑAQUE",
        birthplace: "",
        regDate: "January 9, 2025",
      },
      {
        id: 79,
        name: "LEANDER ADRIAN CAGADAS DOMETITA",
        region: "NCR",
        birthdate: "October 13, 1995",
        tin: "460-341-120",
        email: "leanderadiance@gmail.com",
        mobile: "9272908338",
        address: "2345 GARRIDO ST. STA. ANA MANILA",
        birthplace: "",
        regDate: "January 18, 2025",
      },
      {
        id: 80,
        name: "RAMONELLE GRACE ADOLAR OCHONG",
        region: "NCR",
        birthdate: "June 8, 1993",
        tin: "454-290-122",
        email: "rgochong@gmail.com",
        mobile: "9276808738",
        address: "30F SAN ANTONIO PLACE MALUGAY ST. MAKATI CITY",
        birthplace: "",
        regDate: "January 18 2025",
      },
      {
        id: 81,
        name: "ROCHELE JANE IBAN ONG",
        region: "NCR",
        birthdate: "",
        tin: "417-353-394",
        email: "",
        mobile: "",
        address: "",
        birthplace: "",
        regDate: "January 23, 2025",
      },
      {
        id: 82,
        name: "LORAINE PAULA BAUTISTA SALIVA",
        region: "CENTRAL LUZON",
        birthdate: "November 19, 1992",
        tin: "",
        email: "lorainepaulabautista@gmail.com",
        mobile: "9318710354",
        address: "LA MIRADA ROYALE SUBD. PLARIDEL BULACAN",
        birthplace: "",
        regDate: "February 3, 2025",
      },
      {
        id: 83,
        name: "ALESSANDRA NICOLE LEI SANTOS",
        region: "NCR",
        birthdate: "December 19, 2004",
        tin: "681-310-692",
        email: "alessandranicolelei06@gmail.com",
        mobile: "9985482630",
        address:
          "B10 L6 LILY ST. NEIGHBORHOOD B PARKPLACE VILLAGE ANABU 1D IMUS CAVITE",
        birthplace: "",
        regDate: "February 4, 2025",
      },
      {
        id: 84,
        name: "BAMBI ALITAN MATA",
        region: "",
        birthdate: "April 18, 1980",
        tin: "232-548-793",
        email: "bham_24@yahoo.com",
        mobile: "9199400207/9175847888",
        address: "332 APITONG ST. COMEMBO TAGUIG CITY",
        birthplace: "",
        regDate: "February 5, 2025",
      },
      {
        id: 85,
        name: "KATHERINE GUMAFELIX KHANFAR",
        region: "CENTRAL LUZON",
        birthdate: "March 9, 1979",
        tin: "391-073-179",
        email: "kathydg@gmail.com",
        mobile: "971502576854",
        address: "DUBAI",
        birthplace: "",
        regDate: "February 28, 2025",
      },
      {
        id: 86,
        name: "KIMBERLY JOYCE GARCIA LANGAGAN",
        region: "",
        birthdate: "January 20, 1995",
        tin: "",
        email: "kimlangagan@gmail.com",
        mobile: "971547026858/971509349491",
        address: "DUBAI",
        birthplace: "",
        regDate: "February 16, 2025",
      },
      {
        id: 87,
        name: "HERBERT RAGASA RAGASA",
        region: "",
        birthdate: "March 16, 1984",
        tin: "",
        email: "herbert.ragasa@gmail.com",
        mobile: "971559815028/971503786879",
        address: "DUBAI",
        birthplace: "",
        regDate: "February 16, 2025",
      },
      {
        id: 88,
        name: "MADELEEN MADERAZO ANDRES",
        region: "NCR",
        birthdate: "November 8, 1987",
        tin: "281-701-895",
        email: "gmad2888@gmail.com",
        mobile: "526123747",
        address: "DUBAI",
        birthplace: "",
        regDate: "February 16, 2025",
      },
      {
        id: 89,
        name: "ROMALLA ALONDE VALENCERINA",
        region: "",
        birthdate: "April 11, 1981",
        tin: "",
        email: "lalaalonde@gmail.com",
        mobile: "9206272533",
        address: "DUBAI",
        birthplace: "",
        regDate: "February 16, 2025",
      },
      {
        id: 90,
        name: "DANIEL BONTO JALOS",
        region: "",
        birthdate: "September 13, 1986",
        tin: "624-636-211",
        email: "chef.danieljalos@gmail.com",
        mobile: "971502392249",
        address: "DUBAI",
        birthplace: "",
        regDate: "February 16, 2025",
      },
      {
        id: 91,
        name: "MARIE ROSE BALUCANAG URSUA",
        region: "CALABARZON",
        birthdate: "November 13, 1981",
        tin: "674-356-086",
        email: "maru.ursua@gmail.com",
        mobile: "971555165644",
        address: "DUBAI",
        birthplace: "",
        regDate: "February 16, 2025",
      },
      {
        id: 92,
        name: "AJ LAWRENCE OXINA ARABA",
        region: "CENTRAL LUZON",
        birthdate: "January 14, 1997",
        tin: "768-596-343",
        email: "ajlawrencearaba@gmail.com",
        mobile: "9778023693",
        address: "PH2 BLK 4 LOT 4 CAMELLA FIORENZA PALIGUI APALIT PAMPANGA",
        birthplace: "",
        regDate: "February 21, 2025",
      },
      {
        id: 93,
        name: "LEAH DELA CRUZ MALSI",
        region: "NCR",
        birthdate: "July 23, 2025",
        tin: "674-805-329",
        email: "leahmalsi@gmail.com",
        mobile: "9272364386",
        address: "DUBAI",
        birthplace: "",
        regDate: "February 24, 2025",
      },
      {
        id: 94,
        name: "APRIL JOY RUPAN PANGAN",
        region: "",
        birthdate: "September 23, 1987",
        tin: "765-913-546",
        email: "aprilpangan3@gmail.com",
        mobile: "9671781034",
        address: "BRGY. SAN BARTOLOME SAN PABLO CITY PUROK 4",
        birthplace: "",
        regDate: "March 1, 2025",
      },
      {
        id: 95,
        name: "ROYCE KAMILLE REYES SALEN",
        region: "CENTRAL LUZON",
        birthdate: "April 25, 1987",
        tin: "305-476-681",
        email: "admin@211dragonholdings.com",
        mobile: "9178813211",
        address:
          "8 LEBANON ST. GREENHEIGHTS SUBD. PHASE III NANGKA MARIKINA CITY",
        birthplace: "",
        regDate: "March 1, 2025",
      },
      {
        id: 96,
        name: "JHUN DHICK RAMOS TERRENAL",
        region: "CENTRAL LUZON",
        birthdate: "May 14, 1995",
        tin: "",
        email: "jhundhick@gmail.com",
        mobile: "9172710645",
        address:
          "29A VILLA SEVERA TOWNHOMES RAMIREZ SUBD. NOVALICHES QUEZON CITY",
        birthplace: "",
        regDate: "March 10, 2025",
      },
      {
        id: 97,
        name: "SHAHA AL JOUBORI META",
        region: "CALABARZON",
        birthdate: "May 21, 1996",
        tin: "",
        email: "iishayy.m@gmail.com",
        mobile: "9763291608",
        address:
          "MONDE RESIDENCES BLK 2 LOT 21 CONGRESSIONAL AVE. SALITRAN III DASMARIÑAS CITY CAVITE",
        birthplace: "",
        regDate: "March 15, 2025",
      },
      {
        id: 98,
        name: "GEM MARIELLE LIM NGO",
        region: "NCR",
        birthdate: "May 21, 2025",
        tin: "430-689-120",
        email: "gemlim06@gmail.com",
        mobile: "9175657200",
        address: "P15-14 6TH ST. VILLAMOR AIR BASE PASAY CITY",
        birthplace: "MANILA",
        regDate: "May 21, 2025",
      },
      {
        id: 99,
        name: "REYNALYN FRANCISCO PASCUAL",
        region: "",
        birthdate: "April 2, 1994",
        tin: "708-275-245-000",
        email: "reynalyn.pascual123@gmail.com",
        mobile: "9069664212",
        address: "1304 CAINGIN BOCAUE BULACAN",
        birthplace: "STA MARIA BULACAN",
        regDate: "March 15, 2025",
      },
      {
        id: 100,
        name: "CYRINE JOY C PANGANIBAN",
        region: "",
        birthdate: "February 14, 1987",
        tin: "493-311-011",
        email: "cyrinejoypanganiban@yahoo.com",
        mobile: "9391789615",
        address: "BRGY. SAMALA II SARIAYA QUEZON",
        birthplace: "",
        regDate: "March 20, 2025",
      },
      {
        id: 101,
        name: "SHAINA ELLYCE SUBIDA BATAY",
        region: "CENTRAL LUZON",
        birthdate: "",
        tin: "322-325-240",
        email: "",
        mobile: "",
        address: "",
        birthplace: "",
        regDate: "March 26, 2025",
      },
      {
        id: 102,
        name: "DIANA DE TORRES BELENO",
        region: "NCR",
        birthdate: "August 11, 1982",
        tin: "245-041-964",
        email: "diana_beleno@yahoo.com",
        mobile: "9608704894",
        address: "OUR HOME 2023 GEN. RICARSE ST. TAGUIG CITY",
        birthplace: "",
        regDate: "March 25, 2025",
      },
      {
        id: 103,
        name: "LAVINIA CORTEZ POTO",
        region: "NCR",
        birthdate: "June 18, 1993",
        tin: "466-472-306",
        email: "potolove1827@gmail.com",
        mobile: "9686026118/9166979636",
        address: "K BLDG. UNIT 1633 URBAN DECA HOMES ORTIGAS AVENUE PASIG CITY",
        birthplace: "",
        regDate: "March 26, 2025",
      },
      {
        id: 104,
        name: "CHARMAINE GABOT ALVARADO",
        region: "CENTAL LUZON",
        birthdate: "October 17, 1994",
        tin: "455-847-145",
        email: "alvaradocharmaineg@gmail.com",
        mobile: "9055898878",
        address: "#55 STO. NIÑO BINALONAN PANGASINAN",
        birthplace: "",
        regDate: "April 4, 2025",
      },
      {
        id: 105,
        name: "MARIA CRISELLE VIVIENNE LAPUT CABREDO - PARTOSA",
        region: "",
        birthdate: "September 26, 1984",
        tin: "",
        email: "cris.partos@gmail.com",
        mobile: "9985754708",
        address: "5N CLUSTER 6 BAYSHORE RESIDENTIAL RESORT I TAMBO PARAÑAQUE",
        birthplace: "",
        regDate: "April 4, 2025",
      },
      {
        id: 106,
        name: "ANNAMY PEÑAFLOR RICHARDS",
        region: "",
        birthdate: "September 21, 1986",
        tin: "",
        email: "annamyrichards@yahoo.com.au",
        mobile: "61420295761",
        address:
          "13 MILEHAM CIRCUIT RUTHERFORD NSW 7123 / BACOLOD CITY NEGROS OCCIDENTAL",
        birthplace: "",
        regDate: "April 5, 2025",
      },
      {
        id: 107,
        name: "ROSALINDA CASTRO REYES",
        region: "",
        birthdate: "October 2, 1973",
        tin: "",
        email: "jairynenterprise@gmail.com",
        mobile: "9175621799",
        address:
          "12 ANGELA BUTTE ST. STERLING LIFE HOMES PAMPLONA DOS LAS PIÑAS CITY",
        birthplace: "",
        regDate: "April 10, 2025",
      },
      {
        id: 108,
        name: "MARCO GABRIEL CRUZ",
        region: "",
        birthdate: "June 8, 1967",
        tin: "760-459-076",
        email: "cruzmarcogabriel2001@gmail.com",
        mobile: "9950180470",
        address: "53 SAN ISIDRO ST. RENAISSANCE HILLS KAPITOLYO PASIG CITY",
        birthplace: "",
        regDate: "April 14, 2025",
      },
      {
        id: 109,
        name: "MARIA BERNADETTE CASTRO MANDAP",
        region: "CENTRAL LUZON",
        birthdate: "September 30, 1976",
        tin: "",
        email: "mandapmbernadette30@gmail.com",
        mobile: "9975570890",
        address: "350 ZONE 2 CANSINALA APALIT PAMPANGA",
        birthplace: "",
        regDate: "April 24, 2025",
      },
      {
        id: 110,
        name: "FRANCESCA SELINE DEONA JACOB",
        region: "OTHERS",
        birthdate: "August 15, 1992",
        tin: "436-527-079",
        email: "frankiedeona@gmail.com",
        mobile: "9179266447",
        address: "416 SWEETHOMES WASHINGTON DRIVE LEGAZPI CITY",
        birthplace: "",
        regDate: "April 28, 2025",
      },
      {
        id: 111,
        name: "BEEM KASTEN PADLAN",
        region: "",
        birthdate: "April 27 1982",
        tin: "",
        email: "beemkastenpadlan@yahoo.com",
        mobile: "9285244470",
        address: "224 TOM CAT STREET JLA SUB.LANANG DAVAO CITY",
        birthplace: "",
        regDate: "June 8 2015",
      },
      {
        id: 112,
        name: "KATHERINE ESCALONA- TOLINGAN",
        region: "",
        birthdate: "January 8 1984",
        tin: "",
        email: "katherineescalonatolingan@gmail.com",
        mobile: "9989850065",
        address: "38 PARAMOUNT VILLAGE STO.TOMAS PROPER BAGUIO CITY",
        birthplace: "",
        regDate: "May 21 2025",
      },
      {
        id: 113,
        name: "ALEX BALDERAMA JULIAN",
        region: "",
        birthdate: "August 4 1997",
        tin: "714-775-085",
        email: "lexjulian33@gmail.com",
        mobile: "9368206402",
        address: "B5 L12 KAHAYA AVE ZONE 3,DASMARINAS CAVITE",
        birthplace: "",
        regDate: "June 16 2025",
      },
      {
        id: 114,
        name: "AMARAH JEAN BARRETO",
        region: "",
        birthdate: "June 4 1998",
        tin: "350-576-875",
        email: "amarahj.barretto@gmail.com",
        mobile: "9068577491",
        address: "DE LIMA SUBD BRGY IBABA SANTA ROSA CITY LAGUNA",
        birthplace: "",
        regDate: "June 17 2025",
      },
      {
        id: 115,
        name: "KARL VINCENT OPANA MANALIGOD",
        region: "CENTRAL LUZON",
        birthdate: "October 25 1995",
        tin: "332-238-882",
        email: "patricianicolejalgalado@gmail.com",
        mobile: "9171034097",
        address: "B6 L34 VERDE HEIGHTS SUB. CSJDM BULACAN",
        birthplace: "",
        regDate: "May 15 2025",
      },
      {
        id: 116,
        name: "DARWIN BONDAD ALCANTARA",
        region: "",
        birthdate: "July 9 1987",
        tin: "254-955-703",
        email: "darwinalcantara434@gmail.com",
        mobile: "9062788379",
        address:
          "PH 215 ETON EMERALD LOFT GARNET ST.ORTIGAS,SAN ANTONIO,CITY OF PASIG",
        birthplace: "",
        regDate: "June 17 2025",
      },
      {
        id: 117,
        name: "LORRIE MAY BEJEC LADAO",
        region: "CALABARZON",
        birthdate: "July 2 2004",
        tin: "332-238-882",
        email: "lorrieladao21@gmail.com",
        mobile: "9953469537",
        address: "sct.tauzon viera resedences Quezon City",
        birthplace: "",
        regDate: "June 19 2025",
      },
      {
        id: 118,
        name: "MIKEE S VELEZ",
        region: "",
        birthdate: "",
        tin: "",
        email: "Karl Vincent Manaligod",
        mobile: "",
        address: "",
        birthplace: "",
        regDate: "",
      },
      {
        id: 119,
        name: "MUTT BENEDICT AUSTRIA RAMILO",
        region: "CALABARZON",
        birthdate: "January 8 1991",
        tin: "",
        email: "mutt.ramilo@gmail.com",
        mobile: "9271649858",
        address: "B 2 L 20 KAISAHAN VILLAGE BRGY BAGONG BAYAN TANAUN BATANGAS",
        birthplace: "",
        regDate: "June 16 2025",
      },
      {
        id: 120,
        name: "RON ERWIN DELA CRUZ",
        region: "CENRAL LUZON",
        birthdate: "September 10 1991",
        tin: "",
        email: "ronerwin5555@gmail.com",
        mobile: "9171104938",
        address: "51 JP RIZAL ST. STA BARBARA BALIUAG BULACAN",
        birthplace: "",
        regDate: "June 19 2025",
      },
      {
        id: 121,
        name: "IZZY SLASH OSBOURNE MAGAYAGA ECLEO",
        region: "",
        birthdate: "January 16, 1992",
        tin: "",
        email: "izdoesit0@gmail.com",
        mobile: "9495526879",
        address: "OUANO CENIZA HEIGHTS SURIGAO CITY",
        birthplace: "",
        regDate: "June 25 2025",
      },
      {
        id: 122,
        name: "ERICKA MATAGA PINEDA",
        region: "",
        birthdate: "April 9 2001",
        tin: "514-528-142",
        email: "pinedaericka@gmail.com",
        mobile: "9169143767",
        address: "B7 L25 CASABLANCA ST.MIRUS RES MABALACAT PAMPANGA",
        birthplace: "",
        regDate: "July 1 2025",
      },
      {
        id: 123,
        name: "JAMIE B DYANGKO- CABUG",
        region: "OTHERS",
        birthdate: "August 20 1991",
        tin: "",
        email: "dyangko.jamie@gmail.com",
        mobile: "9176242822",
        address: "436 KARANGAHAN BOULEVARD BOMBON TABACO CITY ALBAY",
        birthplace: "",
        regDate: "July 17 2025",
      },
      {
        id: 124,
        name: "DANI DANNIELLE ADRIOSULA",
        region: "",
        birthdate: "",
        tin: "",
        email: "",
        mobile: "",
        address: "",
        birthplace: "",
        regDate: "July 11 2025",
      },
      {
        id: 125,
        name: "LUCIA RIN RECLOZADO VIACRUSIS",
        region: "CENTRAL LUZON",
        birthdate: "January 31 1999",
        tin: "350-094-221",
        email: "lucia.viancrusis@gmail.com",
        mobile: "09399146124/0954246445",
        address:
          "MAIN ROAD, MALIGAYA VILLAGE DOLORES CITY SAN FERNANDO PAMPANGA PHILIPPINES",
        birthplace: "",
        regDate: "June 26 2025",
      },
      {
        id: 126,
        name: "FREIDRICH ROBIN CERRO",
        region: "OTHERS",
        birthdate: "March 24 1993",
        tin: "",
        email: "REVELOMARJORIE@GMAIL.COM",
        mobile: "09176238723/09778012616",
        address:
          "0077 NATIONAL HIGHWAY ZONE 1 BRGY TIGUMA PAGADIAN CITY ZAMBOANGA DEL SUR,7016",
        birthplace: "",
        regDate: "June 20 2025",
      },
      {
        id: 127,
        name: "DAN ALLEN DE GUZMAN",
        region: "NCR",
        birthdate: "July 29 1987",
        tin: "",
        email: "plukdan.deguzman@gmail.com",
        mobile: "9275521323",
        address: "113 KABALITANG ST. KRUS NA LIGAS QUEZON CITY",
        birthplace: "",
        regDate: "July 9 2025",
      },
      {
        id: 128,
        name: "CARLITO A. JIMENEZ",
        region: "",
        birthdate: "September 26 1961",
        tin: "270-988-478",
        email: "litojim100@gmail.com",
        mobile: "9063552121",
        address: "",
        birthplace: "",
        regDate: "July 4 2025",
      },
      {
        id: 129,
        name: "JOANA MARIE AMANSEC ALEJANDRO",
        region: "",
        birthdate: "May 29 1985",
        tin: "",
        email: "jmaa85@rocketmail.com",
        mobile: "9178515877",
        address: "B62-3 LONGINOS ST GREATER LAGRO QUEZON CITY",
        birthplace: "",
        regDate: "July 5 2025",
      },
      {
        id: 130,
        name: "JANICE MANAGO DORADO",
        region: "",
        birthdate: "June 1 1986",
        tin: "458-012-141-000",
        email: "ecinaj.ouc@gmail.com",
        mobile: "9063705437",
        address: "SORSOGON/WORKING IN GOOGLE BGC TAGUIG",
        birthplace: "",
        regDate: "July 5 2025",
      },
      {
        id: 131,
        name: "ERICA CORTES",
        region: "",
        birthdate: "November 13 1980",
        tin: "225-525-391",
        email: "ecortes13@starboneinternational",
        mobile: "9175891880",
        address: "Chateau De Baie Condominium Corporation",
        birthplace: "",
        regDate: "July 2 2025",
      },
      {
        id: 132,
        name: "PRINCESS QUEENIE B. TATLONGHARI",
        region: "",
        birthdate: "July 17 1994",
        tin: "",
        email: "ptatlonghari.rn@gmail.com",
        mobile: "",
        address: "2727 E. MURDOCK LN ONTARIO CALIFORNIA",
        birthplace: "",
        regDate: "June 30 2025",
      },
      {
        id: 133,
        name: "HAZEL JOY V JAMISON",
        region: "CALABARZON",
        birthdate: "May 16 1984",
        tin: "",
        email: "hazel_jamison@yahoo.com",
        mobile: "4447311658425",
        address: "",
        birthplace: "",
        regDate: "July 7 2025",
      },
      {
        id: 134,
        name: "BARBARA CANADA LUMANOG",
        region: "",
        birthdate: "December 4 1973",
        tin: "191-316-979",
        email: "",
        mobile: "09175341273/09478902973",
        address: "58-D SAN ISIDRO ST. KAPITOLYO PASIG CITY",
        birthplace: "",
        regDate: "July 11 2025",
      },
      {
        id: 135,
        name: "SHIONELY PEDINO BOLA SANTOS",
        region: "",
        birthdate: "",
        tin: "433-251-019",
        email: "shionely.santos@gmail.com",
        mobile: "",
        address: "",
        birthplace: "",
        regDate: "July 11 2025",
      },
      {
        id: 136,
        name: "RENNALYN CRESPO LLANTINO",
        region: "",
        birthdate: "August 15 1987",
        tin: "320-643-638",
        email: "rhencrespo@gmail.com",
        mobile: "9512302434",
        address:
          "BALI OASIS 1 BU4510 MARCOS HIGHWAY STREET BRGY SANTOLAN PASIG CITY",
        birthplace: "",
        regDate: "July 12 2025",
      },
      {
        id: 137,
        name: "JESSICA ESTACIO LIWAG / MR. ED VICTOR MAGBANUA",
        region: "",
        birthdate: "December 7 1996",
        tin: "437-164-422/338-773-035",
        email: "jlestacio7@gmail.com",
        mobile: "9155853579",
        address:
          "B 32 L14B SAN PABLO ST. BRGY SAN ANTONIO VALLEY 1 PARANAQUE CITY",
        birthplace: "",
        regDate: "July 11 2025",
      },
      {
        id: 138,
        name: "EDUARDO SOCO INTERIOR JR.",
        region: "CAGAYAN VALLEY",
        birthdate: "December 11 1998",
        tin: "487-559-768",
        email: "eduardojr.interior@gmail.com",
        mobile: "9171004288",
        address: "UP TOWN RITZ BGC TAGUIG",
        birthplace: "",
        regDate: "July 14 2025",
      },
      {
        id: 139,
        name: "PRINCESS ANGEL F CASAO",
        region: "",
        birthdate: "April 01 1997",
        tin: "",
        email: "princessangelcasao@gmail.com",
        mobile: "9452560932",
        address: "15 MAXIMO FLORES JR. ST.BRGY CANIOGAN PASIG CITY",
        birthplace: "",
        regDate: "July 14 2025",
      },
      {
        id: 140,
        name: "EARLE NESTOR SANTOS REGANIT",
        region: "CENTRAL LUZON",
        birthdate: "March 13 1995",
        tin: "453-624-633",
        email: "rosehrlee0227@gmail.com",
        mobile: "9156472809",
        address:
          "TUNGKO MANGA HOME WARD HOMES BLOCK 7 LOT 1 SAN JOSE DEL MONTE BULACAN",
        birthplace: "",
        regDate: "July 16 2025",
      },
      {
        id: 141,
        name: "APPLE JANE SAN AGUSTIN GARRIDO",
        region: "",
        birthdate: "November 28 1986",
        tin: "",
        email: "",
        mobile: "9175611016",
        address:
          "UNIT A BLK 21 LOT 11 LANGKA STREET. DONA JOSEFA VILLAGE ALMANZA UNO LASPINAS CITY",
        birthplace: "",
        regDate: "July 17 2015",
      },
      {
        id: 142,
        name: "KAREN KEITH P MATINING",
        region: "",
        birthdate: "August 4 2025",
        tin: "167-467-567",
        email: "keithmatining@mail.com",
        mobile: "9666942682",
        address: "BLACK 7 LOT 8 SUNNYDALE VILLAS MALAGASANG 1-B IMUS CAVITE",
        birthplace: "",
        regDate: "July 17 2025",
      },
      {
        id: 143,
        name: "LAWRENCE LEO K PELAEZ / CARLA JOY CASTILLO",
        region: "",
        birthdate: "March 3 1985",
        tin: "",
        email: "",
        mobile: "9171469753",
        address:
          "B24 THE HEIGHTS BRGY MALAZA FREEPORT AREA OF BATAAN, MARIVELES BATAAN",
        birthplace: "",
        regDate: "July 19 2025",
      },
      {
        id: 144,
        name: "NESLEE CASTILLO NARCISO",
        region: "",
        birthdate: "June 12 1992",
        tin: "",
        email: "imneslee@gmail.com",
        mobile: "9098175079",
        address: "The Connor at Greenhills",
        birthplace: "",
        regDate: "July 6 2025",
      },
      {
        id: 145,
        name: "MARY JOY SIAPNO BORNOLLA",
        region: "",
        birthdate: "",
        tin: "",
        email: "",
        mobile: "",
        address: "",
        birthplace: "",
        regDate: "May 16, 2025",
      },
      {
        id: 146,
        name: "NOVRIL B. MANDIIT",
        region: "",
        birthdate: "August 8 1989",
        tin: "297-123-800",
        email: "iamnovril@gmail.com",
        mobile: "9763222256",
        address:
          "BLK 1 LOT 3 CAVITE STREET GENEROSA VILLA CASILI CITY BINAN LAGUNA",
        birthplace: "",
        regDate: "July 28 2025",
      },
      {
        id: 147,
        name: "JUSTINE GAIL BERENGUER",
        region: "",
        birthdate: "February 15 1989",
        tin: "",
        email: "mmm4model@gmail.com/berenguerjustine@gmail.com",
        mobile: "9542982028",
        address: "8469 WEST SERVICE RD BRGY. SUN VALLEY PARANAQUE CITY",
        birthplace: "MAKATI CITY",
        regDate: "July 30, 2025",
      },
      {
        id: 148,
        name: "DREMYL HOMBREBUENO GARCIA",
        region: "",
        birthdate: "February 06, 1992",
        tin: "",
        email: "dremyl.garcia@gmail.com",
        mobile: "9064319290",
        address:
          "P9 B48 L31-33 SAVINHILL ST. GOVERNOR'S HILLS SUBD. BICLATAN, GENERAL TRIAS CAVITE",
        birthplace: "BAGUIO BENGUET",
        regDate: "August 22, 2025",
      },
      {
        id: 149,
        name: "CAREN BALINTONG ZUNIGA",
        region: "",
        birthdate: "September 15, 1991",
        tin: "",
        email: "caren.koko15@yahoo.com",
        mobile: "9151991485",
        address: "BLK. LOT 24 #2C ABFIIA ST. SANVILLE HOMES, BULAK RD. BULACAN",
        birthplace: "BULACAN",
        regDate: "August 21, 2025",
      },
      {
        id: 150,
        name: "MARLON BANARES SANTOS",
        region: "NCR",
        birthdate: "July 22, 1995",
        tin: "447-925-715",
        email: "ymcmarlon@gmail.com",
        mobile: "9772592024",
        address:
          "BLK PH 8A4 MEADOWOOD ST. COR. CAMPANILLA ST. GREENWOODS EXECUTIVE VILLAGE CAINTA RIZAL",
        birthplace: "SAN ISIDRO NUEVA ECIJA",
        regDate: "August 26, 2025",
      },
      {
        id: 151,
        name: "MARIA MARGARITA M. ACABAN",
        region: "",
        birthdate: "",
        tin: "",
        email: "",
        mobile: "",
        address: "",
        birthplace: "",
        regDate: "August 14, 2025",
      },
      {
        id: 152,
        name: "JANINE SANDOVAL MEDINA",
        region: "NCR",
        birthdate: "August 18, 1995",
        tin: "",
        email: "jnamedina1995@gmail.com",
        mobile: "09687459738 / 09637146077",
        address: "2193 Angel Linao Malate Manila",
        birthplace: "Los Banos Laguna",
        regDate: "September 12, 2025",
      },
      {
        id: 153,
        name: "RECHEL MACALALAD HOCO",
        region: "",
        birthdate: "",
        tin: "",
        email: "",
        mobile: "558591758",
        address: "",
        birthplace: "",
        regDate: "September 7, 2025",
      },
      {
        id: 154,
        name: "JOANNA ANTIGO MOLETA",
        region: "",
        birthdate: "",
        tin: "",
        email: "joanna.antigo@yahoo.com",
        mobile: "506947855",
        address: "",
        birthplace: "",
        regDate: "September 7, 2025",
      },
      {
        id: 155,
        name: "AMIEL ANGELO APOSTOL AGUINIR",
        region: "",
        birthdate: "",
        tin: "",
        email: "aguiniramiel318@gmail.com",
        mobile: "581208668",
        address: "",
        birthplace: "",
        regDate: "September 7, 2025",
      },
      {
        id: 156,
        name: "CHARMAINE RAZEL ESTRADA",
        region: "",
        birthdate: "",
        tin: "",
        email: "charmainerazelestrada@gmail.com",
        mobile: "554478173",
        address: "",
        birthplace: "",
        regDate: "September 7, 2025",
      },
      {
        id: 157,
        name: "CHERRY LYN DELICANO SIA",
        region: "",
        birthdate: "",
        tin: "",
        email: "benjaminmsia@gmail.com",
        mobile: "05265005990529044123+971526500599",
        address: "",
        birthplace: "",
        regDate: "September 7, 2025",
      },
      {
        id: 158,
        name: "ANN CHAZELLE ALCANTARA",
        region: "",
        birthdate: "August 20, 1978",
        tin: "208-969-115",
        email: "chaze_alcantara@yahoo.com",
        mobile: "6591116079",
        address: "8K CHELSEA CAPITAL TOWN, SAN FERNANDO PAMPANGA",
        birthplace: "",
        regDate: "September12, 2025",
      },
      {
        id: 159,
        name: "ZEINAB HARAKE - PARKS",
        region: "",
        birthdate: "",
        tin: "",
        email: "",
        mobile: "",
        address: "",
        birthplace: "",
        regDate: "",
      },
      {
        id: 160,
        name: "BOBBY RAY PARKS JR.",
        region: "",
        birthdate: "",
        tin: "",
        email: "",
        mobile: "",
        address: "",
        birthplace: "",
        regDate: "",
      },
      {
        id: 161,
        name: "JELAI ANDRES",
        region: "",
        birthdate: "",
        tin: "",
        email: "",
        mobile: "",
        address: "",
        birthplace: "",
        regDate: "",
      },
      {
        id: 162,
        name: "RODNIE ORBE VALERIO",
        region: "",
        birthdate: "August 23, 1992",
        tin: "455-601-896",
        email: "rodnievalerio@yahoo.com",
        mobile: "9087361684",
        address: "",
        birthplace: "",
        regDate: "September 24, 2025",
      },
      {
        id: 163,
        name: "JENNELYN GONZALES BATHAN",
        region: "",
        birthdate: "May 14, 1992",
        tin: "",
        email: "gonzalesjhen1428@gmail.com",
        mobile: "9929552040",
        address: "",
        birthplace: "",
        regDate: "October 4, 2025",
      },
      {
        id: 164,
        name: "KIMBERLY COLORADO",
        region: "",
        birthdate: "",
        tin: "",
        email: "",
        mobile: "",
        address: "",
        birthplace: "",
        regDate: "September 16, 2025",
      },
      {
        id: 165,
        name: "DENISE FRANCISCO",
        region: "",
        birthdate: "",
        tin: "",
        email: "",
        mobile: "",
        address: "",
        birthplace: "",
        regDate: "September 30, 2025",
      },
      {
        id: 166,
        name: "ROSEMARIE VALITE",
        region: "",
        birthdate: "",
        tin: "",
        email: "",
        mobile: "",
        address: "",
        birthplace: "",
        regDate: "October 11, 2025",
      },
    ];

    rawData.forEach((franchisee) => {
      // Clean up name for uniqueness check
      const name = franchisee.name
        .toUpperCase()
        .replace(/\s*\([\s\S]*?\)\s*/g, "") // Remove content in parentheses
        .trim();

      if (!franchiseeMap.has(name)) {
        franchiseeMap.set(name, franchisee);
      }
    });

    const uniqueFranchisees = Array.from(franchiseeMap.values());
    console.log(uniqueFranchisees);
    // ... rest of your processing logic
    // Helper function to generate franchisee ID in B1T1YY-XXX0 format
    const generateFranchiseeId = (regDate: string, originalId: number) => {
      if (!regDate) return `B1T1-${originalId.toString().padStart(3, "0")}`;

      // Extract year from regDate (format: "Month Day, Year" or "Month Day Year")
      const yearMatch = regDate.match(/(\d{4})/);
      if (!yearMatch) return `B1T1-${originalId.toString().padStart(3, "0")}`;

      const year = yearMatch[1];
      const lastTwoDigits = year.slice(-2);
      const paddedId = originalId.toString().padStart(3, "0");

      return `B1T1${lastTwoDigits}-${paddedId}0`;
    };

    const parseName = (fullName: string) => {
      const cleanName = fullName
        .replace(/\s*\(\d+\)|\s*\(AGFI\)|\s*\(TRANSFER.*?\)/gi, "")
        .trim();
      const parts = cleanName
        .split(" ")
        .filter((part: string) => part.length > 0);

      if (parts.length === 0) {
        return { firstName: "", lastName: "" };
      } else if (parts.length === 1) {
        return { firstName: parts[0], lastName: "" };
      } else if (parts.length === 2) {
        return { firstName: parts[0], lastName: parts[1] };
      } else {
        // Handle special cases for Filipino names
        let firstName = parts[0];
        let lastName = parts[parts.length - 1];

        // Handle names ending with "Jr." or "Junior"
        if (
          parts[parts.length - 1].toLowerCase() === "jr." ||
          parts[parts.length - 1].toLowerCase() === "junior"
        ) {
          lastName = parts[parts.length - 2]; // Take the word before Jr./Junior
        }

        // Handle names starting with "Ma."
        if (parts[0].toLowerCase() === "ma." && parts.length > 1) {
          firstName = parts[0] + " " + parts[1]; // Combine "Ma." with the next word
        }

        return {
          firstName,
          lastName,
        };
      }
    };

    // Process data into Excel format
    const excelData = uniqueFranchisees.map((item) => {
      const { firstName, lastName } = parseName(item.name);
      const franchiseeId = generateFranchiseeId(item.regDate, item.id);
      return {
        "Franchisee ID": franchiseeId,
        "First Name": firstName,
        "Last Name": lastName,
        Nickname: "",
        Gender: "",
        "Birth Date": item.birthdate,
        "Birth Place": item.birthplace,
        Nationality: "Filipino",
        "Civil Status": "",
        TIN: item.tin,
        "Location Tag": item.region === "OTHERS" ? "" : item.region,
        "Residential Address": item.address,
        Email: item.email,
        "Mobile Number": item.mobile,
        Telephone: "",
        "Current Occupation": "",
        "Company Name": "",
        "Length of Stay": "",
        "Work Address": "",
        "Preferred Location": "",
        "Registration Date": item.regDate,
      };
    });

    return excelData;
  };

  const downloadExcel = () => {
    setProcessing(true);

    setTimeout(() => {
      const data = processData();

      // Create CSV content
      const headers = Object.keys(data[0]).join(",");
      const rows = data.map((row) =>
        Object.values(row)
          .map((val) => {
            const str = String(val || "");
            return str.includes(",") ? `"${str}"` : str;
          })
          .join(",")
      );

      const csvContent = [headers, ...rows].join("\n");
      const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
      const link = document.createElement("a");
      link.href = URL.createObjectURL(blob);
      link.download = "franchisee_data.csv";
      link.click();

      setProcessing(false);
    }, 500);
  };

  return (
    <div className="container mx-auto p-6 bg-white rounded-lg shadow-lg max-w-4xl">
      <div className="flex flex-col md:flex-row md:items-start">
        <div className="md:w-1/2 md:pr-8">
          <h2 className="text-2xl font-bold text-gray-800 mb-4">
            Franchisee Data Processor
          </h2>
          <p className="text-gray-600 mb-6">
            Upload your raw franchisee data file (.xlsx, .csv) to process and
            clean it for database import.
          </p>
          <button
            onClick={downloadExcel}
            disabled={processing}
            className={`w-full flex items-center justify-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 ${
              processing ? "opacity-50 cursor-not-allowed" : ""
            }`}
          >
            <Download className="mr-2 h-5 w-5" />
            {processing ? "Processing..." : "Process and Download CSV"}
          </button>
        </div>
        <div className="md:w-1/2 mt-8 md:mt-0 md:pl-8 border-t md:border-t-0 md:border-l border-gray-200 pt-8 md:pt-0">
          <div>
            <h3 className="text-lg font-semibold text-gray-700">
              Output Format
            </h3>
            <div className="mt-3 bg-gray-50 p-4 rounded-lg">
              <p className="text-sm text-gray-600 font-medium">
                The output will be a single{" "}
                <code className="text-xs bg-gray-200 px-1 py-0.5 rounded">
                  franchisees.csv
                </code>{" "}
                file.
              </p>
              <p className="mt-1 text-sm text-gray-600">
                You can open it in Excel, Google Sheets, or any spreadsheet
                application
              </p>
            </div>
          </div>

          <div className="mt-8 pt-6 border-t border-gray-200">
            <h3 className="text-lg font-semibold text-gray-700 mb-3">
              Output Columns
            </h3>
            <div className="grid grid-cols-2 md:grid-cols-3 gap-2 text-sm text-gray-600">
              {[
                "Franchisee ID",
                "First Name",
                "Last Name",
                "Nickname",
                "Gender",
                "Birth Date",
                "Birth Place",
                "Nationality",
                "Civil Status",
                "TIN",
                "Location Tag",
                "Residential Address",
                "Email",
                "Mobile Number",
                "Telephone",
                "Current Occupation",
                "Company Name",
                "Length of Stay",
                "Work Address",
                "Preferred Location",
                "Registration Date",
              ].map((col) => (
                <span
                  key={col}
                  className="bg-gray-100 px-2 py-1 rounded text-xs"
                >
                  {col}
                </span>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default FranchiseeDataProcessor;
